CREATE TABLE public.feed_capacity_fixture(id boolean PRIMARY KEY CHECK(id), fixture_version text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO public.feed_capacity_fixture VALUES(true,'synthetic-capacity-v1',now());
INSERT INTO feed.users(github_id,login,taxonomy_version,profile_version)
 SELECT 900000001+i,'capacity-user-'||i,1,1 FROM generate_series(0,4999) i;
CREATE TABLE public.feed_capacity_receipts(receipt_id text PRIMARY KEY,repo_key text UNIQUE NOT NULL,github_id bigint REFERENCES feed.users(github_id) ON DELETE SET NULL,source_kind text NOT NULL CHECK(source_kind='app_submission'),submitted_at timestamptz NOT NULL);
INSERT INTO public.feed_capacity_receipts SELECT 'synthetic-capacity-receipt-'||i, 'capacity-owner-'||lpad((i%10000)::text,5,'0')||'/synthetic-project-'||lpad(i::text,5,'0'),900000001+i/10,'app_submission',now()-interval '20 days' FROM generate_series(0,49999) i;
CREATE TABLE public.feed_capacity_assessments(analysis_id text PRIMARY KEY,receipt_id text NOT NULL REFERENCES public.feed_capacity_receipts(receipt_id),repo_key text UNIQUE NOT NULL,completed boolean NOT NULL CHECK(completed),analysis_json jsonb NOT NULL);
INSERT INTO public.feed_capacity_assessments SELECT 'synthetic-capacity-analysis-'||i,receipt_id,repo_key,true,jsonb_build_object('fixture','synthetic-capacity-v1','completed',true,'productScore',60+i%41,'confidence',80+i%21) FROM public.feed_capacity_receipts r JOIN generate_series(0,49999) i ON r.receipt_id='synthetic-capacity-receipt-'||i;
INSERT INTO feed.projects(repo_key,item_id,owner_login,name,canonical_url,summary,project_type,lifecycle,product_score,confidence,verification_level,exposure_band,treasure_eligible,analysis_id,resolved_commit_sha,analyzed_at,descriptor,descriptor_hash,source_hash,publishable)
 SELECT a.repo_key,replace(a.repo_key,'/',':'),split_part(a.repo_key,'/',1),split_part(a.repo_key,'/',2),'https://github.com/'||a.repo_key,'Synthetic capacity fixture only','cli','usable',(a.analysis_json->>'productScore')::float,(a.analysis_json->>'confidence')::float,'verified','low',true,a.analysis_id,repeat('a',40),now()-make_interval(secs=>i),'synthetic capacity fixture',repeat(md5(a.repo_key),2),repeat(md5(a.analysis_json::text),2),a.completed FROM public.feed_capacity_assessments a JOIN generate_series(0,49999) i ON a.analysis_id='synthetic-capacity-analysis-'||i;
INSERT INTO feed.project_submission_evidence(repo_key,source_kind,source_id,submitted_at,analysis_id)
 SELECT a.repo_key,r.source_kind,r.receipt_id,r.submitted_at,a.analysis_id FROM public.feed_capacity_assessments a JOIN public.feed_capacity_receipts r USING(receipt_id);
INSERT INTO feed.project_tags(repo_key,tag_id,source,weight,confidence,evidence_ids,analysis_id,taxonomy_version)
 SELECT p.repo_key,t.id,'system',0.8,0.9,jsonb_build_array(e.source_id),p.analysis_id,1 FROM feed.projects p JOIN feed.project_submission_evidence e USING(repo_key) CROSS JOIN feed.tag_definitions t WHERE t.id IN('artifact:micro-tool','stage:active-evolution');
INSERT INTO feed.user_tag_preferences(github_id,tag_id,value,source,strength,taxonomy_version) SELECT u.github_id,t.id,1,'explicit',1,1 FROM feed.users u CROSS JOIN feed.tag_definitions t WHERE t.id IN('artifact:micro-tool','stage:active-evolution');
INSERT INTO feed.requests(id,github_id,algorithm_version,taxonomy_version,profile_version,seed,candidate_counts,created_at) SELECT 'synthetic-capacity-request-'||i,900000001+i,'baseline-v2-portable',1,1,'synthetic-capacity-fixture','{"fixture":10}',now()-interval '15 days' FROM generate_series(0,4999) i;
INSERT INTO feed.served_items(request_id,repo_key,rank,candidate_sources,reason_codes,feature_snapshot,score,exploration,propensity,served_at)
 SELECT 'synthetic-capacity-request-'||(i/10),repo_key,i%10,'["quality"]','[]','{}',0.8,false,1,now()-interval '15 days' FROM public.feed_capacity_receipts r JOIN generate_series(0,49999) i ON r.receipt_id='synthetic-capacity-receipt-'||i;
INSERT INTO feed.events(id,github_id,repo_key,request_id,event_type,occurred_at,metadata)
 WITH samples AS (SELECT i,CASE WHEN i<=250000 THEN 0 ELSE 1+((i-250001)%4999) END actor,(i-1)%10 rank FROM generate_series(1,1000000) i)
 SELECT substring(md5('synthetic-capacity-event-'||i),1,8)||'-'||substring(md5('synthetic-capacity-event-'||i),9,4)||'-4'||substring(md5('synthetic-capacity-event-'||i),14,3)||'-8'||substring(md5('synthetic-capacity-event-'||i),18,3)||'-'||substring(md5('synthetic-capacity-event-'||i),21,12),900000001+actor,r.repo_key,'synthetic-capacity-request-'||actor,CASE WHEN i%2=0 THEN 'impression' ELSE 'detail_open' END,now()-interval '15 days'+make_interval(secs=>i%86400),jsonb_build_object('rank',rank,'algorithmVersion','baseline-v2-portable') FROM samples s JOIN public.feed_capacity_receipts r ON r.receipt_id='synthetic-capacity-receipt-'||(actor*10+rank);
