-- Hiring board: companies, open roles, and per-locale copy.
-- Timestamps are Unix milliseconds in UTC. A job is listed while status = 'open'
-- and expires_at is NULL or in the future. Pinned jobs (sponsors) sort first.
-- Translations fall back to en, then zh, when a locale row is missing.
CREATE TABLE IF NOT EXISTS job_companies (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  website_url   TEXT,
  logo_url      TEXT,
  careers_url   TEXT,
  is_sponsor    INTEGER NOT NULL DEFAULT 0 CHECK (is_sponsor IN (0, 1)),
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS jobs (
  id               TEXT PRIMARY KEY,
  company_id       TEXT NOT NULL REFERENCES job_companies(id),
  apply_url        TEXT NOT NULL,
  -- Comma-separated subset of full_time, intern, part_time.
  employment_types TEXT NOT NULL DEFAULT 'full_time',
  status           TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  is_pinned        INTEGER NOT NULL DEFAULT 0 CHECK (is_pinned IN (0, 1)),
  display_order    INTEGER NOT NULL DEFAULT 0,
  expires_at       INTEGER,
  created_at       INTEGER NOT NULL,
  updated_at       INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_jobs_listing
  ON jobs(status, is_pinned DESC, display_order);

CREATE TABLE IF NOT EXISTS job_translations (
  job_id   TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  locale   TEXT NOT NULL,
  title    TEXT NOT NULL,
  category TEXT,
  location TEXT,
  salary   TEXT,
  summary  TEXT,
  PRIMARY KEY (job_id, locale)
);

INSERT INTO job_companies (id, name, website_url, logo_url, careers_url, is_sponsor, display_order, created_at, updated_at) VALUES
  ('modaleap', 'ModaLeap', 'https://www.modaleap.cn', '/modaleap.svg', 'https://www.modaleap.cn/join#jobs', 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek', 'DeepSeek', 'https://www.deepseek.com', '/deepseek.svg', 'https://talent.deepseek.com/', 0, 1, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000);

INSERT INTO jobs (id, company_id, apply_url, employment_types, status, is_pinned, display_order, expires_at, created_at, updated_at) VALUES
  ('modaleap-agent-engineer', 'modaleap', 'https://www.modaleap.cn/join/agent-engineer', 'full_time,intern', 'open', 1, 0, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-fde-delivery-engineer', 'modaleap', 'https://www.modaleap.cn/join/fde-delivery-engineer', 'full_time,intern', 'open', 1, 1, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-ai-gateway-engineer', 'modaleap', 'https://www.modaleap.cn/join/ai-gateway-engineer', 'full_time', 'open', 0, 102, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-open-source-community-intern', 'modaleap', 'https://www.modaleap.cn/join/open-source-community-intern', 'intern', 'open', 0, 103, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-ai-product-test-engineer', 'modaleap', 'https://www.modaleap.cn/join/ai-product-test-engineer', 'full_time,intern', 'open', 0, 104, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-ai-gateway-operations-engineer', 'modaleap', 'https://www.modaleap.cn/join/ai-gateway-operations-engineer', 'full_time', 'open', 0, 105, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-delivery-operations-engineer', 'modaleap', 'https://www.modaleap.cn/join/delivery-operations-engineer', 'full_time', 'open', 0, 106, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-ai-product-after-sales-lead', 'modaleap', 'https://www.modaleap.cn/join/ai-product-after-sales-lead', 'full_time', 'open', 0, 107, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-ai-product-manager', 'modaleap', 'https://www.modaleap.cn/join/ai-product-manager', 'intern', 'open', 0, 108, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-content-operations', 'modaleap', 'https://www.modaleap.cn/join/content-operations', 'full_time,intern', 'open', 0, 109, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-ecosystem-project-manager', 'modaleap', 'https://www.modaleap.cn/join/ecosystem-project-manager', 'full_time', 'open', 0, 110, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-community-operations-intern', 'modaleap', 'https://www.modaleap.cn/join/community-operations-intern', 'intern', 'open', 0, 111, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-sales-manager', 'modaleap', 'https://www.modaleap.cn/join/sales-manager', 'full_time', 'open', 0, 112, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-sales-management-trainee', 'modaleap', 'https://www.modaleap.cn/join/sales-management-trainee', 'intern', 'open', 0, 113, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-channel-development', 'modaleap', 'https://www.modaleap.cn/join/channel-development', 'full_time', 'open', 0, 114, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-channel-business-manager', 'modaleap', 'https://www.modaleap.cn/join/channel-business-manager', 'full_time', 'open', 0, 115, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-hr-specialist', 'modaleap', 'https://www.modaleap.cn/join/hr-specialist', 'full_time,intern', 'open', 0, 116, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-finance-assistant', 'modaleap', 'https://www.modaleap.cn/join/finance-assistant', 'full_time', 'open', 0, 117, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-general-office-intern', 'modaleap', 'https://www.modaleap.cn/join/general-office-intern', 'intern', 'open', 0, 118, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-coo-business-assistant', 'modaleap', 'https://www.modaleap.cn/join/coo-business-assistant', 'full_time', 'open', 0, 119, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-ai-supply-chain-manager', 'modaleap', 'https://www.modaleap.cn/join/ai-supply-chain-manager', 'full_time', 'open', 0, 120, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-training-instructor', 'modaleap', 'https://www.modaleap.cn/join/training-instructor', 'full_time', 'open', 0, 121, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('modaleap-visual-designer-part-time', 'modaleap', 'https://www.modaleap.cn/join/visual-designer-part-time', 'part_time', 'open', 0, 122, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-8d40c764', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/8d40c764-d2b2-49b1-826c-e3f2adb75c01', 'full_time', 'open', 0, 10, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-43f8551a', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/43f8551a-4235-4d5e-a9a7-44386cd79795', 'full_time', 'open', 0, 11, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-2eb2e75d', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/2eb2e75d-29f3-47b5-bb10-39f12547d398', 'full_time', 'open', 0, 12, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-bae809fb', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/bae809fb-1978-4401-b209-34067b26569d', 'full_time', 'open', 0, 13, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-01416da2', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/01416da2-3c8a-4a20-bbb3-1c925d0facf1', 'full_time', 'open', 0, 14, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-8a4c2868', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/8a4c2868-599d-40db-be4d-ab58eec5d7e1', 'full_time', 'open', 0, 15, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-1df4597d', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/1df4597d-6039-4392-9954-0df72510f415', 'full_time', 'open', 0, 16, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-0a317cbb', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/0a317cbb-df30-4770-b0d6-c51bf4e2133b', 'full_time', 'open', 0, 17, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-50733e68', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/50733e68-4b26-4037-8b63-2ed781aa44ed', 'full_time', 'open', 0, 18, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-efc2a5d0', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/efc2a5d0-ac4b-431d-a86a-c23521d8dfdc', 'full_time', 'open', 0, 19, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-cdccf456', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/cdccf456-207f-4ea0-9fdd-c30a5ce42d5b', 'full_time', 'open', 0, 20, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-aed2a32c', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/aed2a32c-189f-4338-b901-9b45d2b7edfd', 'full_time', 'open', 0, 21, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-a63f2346', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/a63f2346-b672-4c48-af43-0a64bfe97a41', 'full_time', 'open', 0, 22, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-a7355097', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/a7355097-fd57-4219-99a5-8963745d362f', 'full_time', 'open', 0, 23, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-b48bdca9', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/b48bdca9-742f-44f1-bde8-5c4e9b953f31', 'full_time', 'open', 0, 24, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-27f0675d', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/27f0675d-5ffd-48d9-a36c-f340a443dc8b', 'full_time', 'open', 0, 25, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-1c7e328d', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/1c7e328d-3da9-4129-a938-21edfd77d38c', 'full_time', 'open', 0, 26, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-e8f2004c', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/e8f2004c-6599-42cd-b587-176ffc3ff1a3', 'full_time', 'open', 0, 27, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-d6cff61d', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/d6cff61d-f03f-4440-8a69-900cb407af5b', 'full_time', 'open', 0, 28, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-a4ad8628', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/a4ad8628-286e-4395-ac3e-b8117ac695c6', 'full_time', 'open', 0, 29, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-bdffaaf8', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/bdffaaf8-5d88-4aa5-9869-8ab76fcd862a', 'full_time', 'open', 0, 30, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-141a78cd', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/141a78cd-784f-4139-9b72-8046afeec4e4', 'full_time', 'open', 0, 31, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-0238c1b1', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/0238c1b1-7f2d-4b53-84da-581127a62954', 'full_time', 'open', 0, 32, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-b8e62d9e', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/b8e62d9e-5cfb-4f24-bb6b-549bf45e1ee0', 'full_time', 'open', 0, 33, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-c7076ca9', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/c7076ca9-558c-4ec3-804b-f21bdfc6135c', 'full_time', 'open', 0, 34, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-25dcb4d9', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/25dcb4d9-d250-43ce-8f56-159ddba47c10', 'full_time', 'open', 0, 35, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-5d75f4cd', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/5d75f4cd-f626-4f73-80c1-e53b2073de76', 'full_time', 'open', 0, 36, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-7dcd6fde', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/7dcd6fde-84f1-4deb-890c-f1f275df0efc', 'full_time', 'open', 0, 37, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-647a8853', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/647a8853-3707-4cb6-a4cd-7e582da27774', 'full_time', 'open', 0, 38, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-08d2d307', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/08d2d307-61f9-4465-ba5f-f8eeb20d675b', 'full_time', 'open', 0, 39, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-7dfbdfc9', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/7dfbdfc9-d61f-481e-ab19-954c10b8f763', 'full_time', 'open', 0, 40, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-2f6838b7', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/2f6838b7-f9ef-457c-8e54-cde45de1f883', 'full_time', 'open', 0, 41, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-97ecb322', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/97ecb322-fa87-47f3-8c1e-e66edfbd34fc', 'full_time', 'open', 0, 42, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('deepseek-a7a0d39e', 'deepseek', 'https://app.mokahr.com/social-recruitment/high-flyer/140576#/job/a7a0d39e-a15b-4dac-909c-0ce26fbb950e', 'full_time', 'open', 0, 43, NULL, CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000);

INSERT INTO job_translations (job_id, locale, title, category, location, salary, summary) VALUES
  ('modaleap-agent-engineer', 'en', 'Agent R&D Engineer', 'R&D', NULL, NULL, 'Build AI-driven tools, model evaluation and full-stack product capabilities, shipping to users and iterating continuously.'),
  ('modaleap-agent-engineer', 'zh', 'Agent 研发工程师', '研发', NULL, NULL, '参与 AI 驱动工具、模型评测与全栈产品能力建设，直接面向用户持续迭代。'),
  ('modaleap-agent-engineer', 'ja', 'Agent 開発エンジニア', '研究開発', NULL, NULL, 'AI 駆動ツール、モデル評価、フルスタックのプロダクト開発に携わり、ユーザーと向き合いながら改善を重ねます。'),
  ('modaleap-agent-engineer', 'ko', 'Agent 개발 엔지니어', '연구개발', NULL, NULL, 'AI 기반 도구, 모델 평가, 풀스택 제품 역량 구축에 참여하며 사용자와 직접 마주하고 지속적으로 개선합니다.'),
  ('modaleap-agent-engineer', 'es', 'Ingeniero de I+D de agentes', 'I+D', NULL, NULL, 'Construye herramientas impulsadas por IA, evaluación de modelos y producto full-stack, iterando de cara al usuario.'),
  ('modaleap-agent-engineer', 'pt', 'Engenheiro de P&D de agentes', 'P&D', NULL, NULL, 'Construa ferramentas movidas a IA, avaliação de modelos e produto full-stack, iterando direto com os usuários.'),
  ('modaleap-agent-engineer', 'id', 'Engineer R&D Agent', 'R&D', NULL, NULL, 'Membangun tool berbasis AI, evaluasi model, dan kapabilitas produk full-stack yang langsung dipakai pengguna.'),
  ('modaleap-agent-engineer', 'vi', 'Kỹ sư R&D Agent', 'R&D', NULL, NULL, 'Xây dựng công cụ dùng AI, đánh giá mô hình và năng lực sản phẩm full-stack, liên tục cải tiến cùng người dùng.'),
  ('modaleap-agent-engineer', 'ar', 'مهندس بحث وتطوير الوكلاء', 'البحث والتطوير', NULL, NULL, 'المشاركة في بناء أدوات مدعومة بالذكاء الاصطناعي وتقييم النماذج وقدرات المنتج المتكاملة مع تطوير مستمر يخدم المستخدمين مباشرة.'),
  ('modaleap-fde-delivery-engineer', 'en', 'Forward Deployed Engineer (FDE)', 'Solutions & Delivery', NULL, NULL, 'Work inside customers'' real businesses to build and ship production Agent apps on LeapOpen.'),
  ('modaleap-fde-delivery-engineer', 'zh', 'FDE（交付工程师）', '解决方案与交付', NULL, NULL, '深入客户真实业务，基于 LeapOpen 开发并交付可上线的 Agent 应用。'),
  ('modaleap-fde-delivery-engineer', 'ja', 'FDE（導入エンジニア）', 'ソリューション・導入', NULL, NULL, '顧客の実業務に入り込み、LeapOpen 上で本番運用できる Agent アプリを開発・導入します。'),
  ('modaleap-fde-delivery-engineer', 'ko', 'FDE (딜리버리 엔지니어)', '솔루션·딜리버리', NULL, NULL, '고객의 실제 업무에 깊이 들어가 LeapOpen 기반으로 실서비스 Agent 애플리케이션을 개발·납품합니다.'),
  ('modaleap-fde-delivery-engineer', 'es', 'Forward Deployed Engineer (FDE)', 'Soluciones y entrega', NULL, NULL, 'Trabaja dentro del negocio real del cliente para construir y entregar apps de agentes en producción sobre LeapOpen.'),
  ('modaleap-fde-delivery-engineer', 'pt', 'Forward Deployed Engineer (FDE)', 'Soluções e entrega', NULL, NULL, 'Atue no negócio real do cliente para construir e entregar apps de agentes em produção sobre o LeapOpen.'),
  ('modaleap-fde-delivery-engineer', 'id', 'Forward Deployed Engineer (FDE)', 'Solusi & delivery', NULL, NULL, 'Terjun ke bisnis nyata pelanggan untuk membangun dan mengirim aplikasi Agent siap produksi di LeapOpen.'),
  ('modaleap-fde-delivery-engineer', 'vi', 'Forward Deployed Engineer (FDE)', 'Giải pháp & triển khai', NULL, NULL, 'Đi sâu vào nghiệp vụ thực tế của khách hàng, phát triển và bàn giao ứng dụng Agent chạy thật trên LeapOpen.'),
  ('modaleap-fde-delivery-engineer', 'ar', 'مهندس النشر الميداني (FDE)', 'الحلول والتسليم', NULL, NULL, 'العمل داخل أعمال العملاء الفعلية لتطوير وتسليم تطبيقات وكلاء جاهزة للإنتاج على LeapOpen.'),
  ('modaleap-ai-gateway-engineer', 'en', 'Gateway Engineer', 'R&D', NULL, NULL, 'Own the gateway subsystem of a unified compute-scheduling platform: performance, stability and security across models and channels.'),
  ('modaleap-ai-gateway-engineer', 'zh', '网关开发工程师', '研发', NULL, NULL, '负责智算算力统一调度平台网关子系统，保障多模型、多通道下的性能、稳定性与安全。'),
  ('modaleap-ai-gateway-engineer', 'ja', 'ゲートウェイ開発エンジニア', '研究開発', NULL, NULL, 'AI 計算資源の統合スケジューリング基盤のゲートウェイを担当し、複数モデル・チャネルでの性能・安定性・安全性を守ります。'),
  ('modaleap-ai-gateway-engineer', 'ko', '게이트웨이 개발 엔지니어', '연구개발', NULL, NULL, 'AI 컴퓨팅 통합 스케줄링 플랫폼의 게이트웨이를 맡아 멀티 모델·멀티 채널 환경의 성능, 안정성, 보안을 책임집니다.'),
  ('modaleap-ai-gateway-engineer', 'es', 'Ingeniero de gateway', 'I+D', NULL, NULL, 'Responsable del gateway de una plataforma unificada de cómputo: rendimiento, estabilidad y seguridad multimodelo y multicanal.'),
  ('modaleap-ai-gateway-engineer', 'pt', 'Engenheiro de gateway', 'P&D', NULL, NULL, 'Responsável pelo gateway de uma plataforma unificada de computação: desempenho, estabilidade e segurança multimodelo e multicanal.'),
  ('modaleap-ai-gateway-engineer', 'id', 'Engineer gateway', 'R&D', NULL, NULL, 'Memegang subsistem gateway platform penjadwalan komputasi terpadu: performa, stabilitas, dan keamanan lintas model dan kanal.'),
  ('modaleap-ai-gateway-engineer', 'vi', 'Kỹ sư gateway', 'R&D', NULL, NULL, 'Phụ trách gateway của nền tảng điều phối tài nguyên tính toán hợp nhất, bảo đảm hiệu năng, ổn định và an toàn đa mô hình, đa kênh.'),
  ('modaleap-ai-gateway-engineer', 'ar', 'مهندس تطوير البوابات', 'البحث والتطوير', NULL, NULL, 'مسؤول عن نظام البوابة في منصة الجدولة الموحدة للحوسبة، لضمان الأداء والاستقرار والأمان عبر نماذج وقنوات متعددة.'),
  ('modaleap-open-source-community-intern', 'en', 'Open-Source Community Intern', 'R&D', NULL, NULL, 'Help develop and maintain the company''s open-source projects, research technology and support community events.'),
  ('modaleap-open-source-community-intern', 'zh', '开源社区实习生', '研发', NULL, NULL, '参与公司开源项目开发维护、技术调研与社区活动支持。'),
  ('modaleap-open-source-community-intern', 'ja', 'オープンソースコミュニティ・インターン', '研究開発', NULL, NULL, '自社オープンソースプロジェクトの開発・保守、技術調査、コミュニティ活動を支援します。'),
  ('modaleap-open-source-community-intern', 'ko', '오픈소스 커뮤니티 인턴', '연구개발', NULL, NULL, '회사 오픈소스 프로젝트 개발·유지보수, 기술 조사, 커뮤니티 활동을 지원합니다.'),
  ('modaleap-open-source-community-intern', 'es', 'Becario de comunidad open source', 'I+D', NULL, NULL, 'Desarrolla y mantiene proyectos open source de la empresa, investiga tecnología y apoya eventos de la comunidad.'),
  ('modaleap-open-source-community-intern', 'pt', 'Estagiário de comunidade open source', 'P&D', NULL, NULL, 'Desenvolva e mantenha projetos open source da empresa, pesquise tecnologias e apoie eventos da comunidade.'),
  ('modaleap-open-source-community-intern', 'id', 'Magang komunitas open source', 'R&D', NULL, NULL, 'Ikut mengembangkan dan memelihara proyek open source perusahaan, riset teknologi, dan mendukung acara komunitas.'),
  ('modaleap-open-source-community-intern', 'vi', 'Thực tập sinh cộng đồng mã nguồn mở', 'R&D', NULL, NULL, 'Tham gia phát triển, bảo trì dự án mã nguồn mở của công ty, nghiên cứu công nghệ và hỗ trợ sự kiện cộng đồng.'),
  ('modaleap-open-source-community-intern', 'ar', 'متدرب مجتمع المصادر المفتوحة', 'البحث والتطوير', NULL, NULL, 'المشاركة في تطوير مشاريع الشركة مفتوحة المصدر وصيانتها، والبحث التقني، ودعم فعاليات المجتمع.'),
  ('modaleap-ai-product-test-engineer', 'en', 'QA Engineer (AI Products)', 'Testing & Ops', NULL, NULL, 'Test critical paths of AI products, web and multi-platform apps, and close the loop on quality risks.'),
  ('modaleap-ai-product-test-engineer', 'zh', '测试工程师（AI 产品）', '测试与运维', NULL, NULL, '负责 AI 产品及 Web、多端应用的关键链路测试，推动质量风险闭环。'),
  ('modaleap-ai-product-test-engineer', 'ja', 'テストエンジニア（AI プロダクト）', 'テスト・運用', NULL, NULL, 'AI プロダクトや Web・マルチプラットフォームアプリの重要経路をテストし、品質リスクを解消まで追います。'),
  ('modaleap-ai-product-test-engineer', 'ko', '테스트 엔지니어 (AI 제품)', '테스트·운영', NULL, NULL, 'AI 제품과 웹·멀티플랫폼 앱의 핵심 경로를 테스트하고 품질 리스크를 끝까지 해결합니다.'),
  ('modaleap-ai-product-test-engineer', 'es', 'Ingeniero de QA (productos de IA)', 'Pruebas y operaciones', NULL, NULL, 'Prueba los flujos críticos de productos de IA, web y apps multiplataforma, y cierra los riesgos de calidad.'),
  ('modaleap-ai-product-test-engineer', 'pt', 'Engenheiro de QA (produtos de IA)', 'Testes e operações', NULL, NULL, 'Teste os fluxos críticos de produtos de IA, web e apps multiplataforma e feche os riscos de qualidade.'),
  ('modaleap-ai-product-test-engineer', 'id', 'Engineer QA (produk AI)', 'Pengujian & operasional', NULL, NULL, 'Menguji jalur kritis produk AI, web, dan aplikasi multiplatform serta menuntaskan risiko kualitas.'),
  ('modaleap-ai-product-test-engineer', 'vi', 'Kỹ sư kiểm thử (sản phẩm AI)', 'Kiểm thử & vận hành', NULL, NULL, 'Kiểm thử các luồng then chốt của sản phẩm AI, web và ứng dụng đa nền tảng, xử lý dứt điểm rủi ro chất lượng.'),
  ('modaleap-ai-product-test-engineer', 'ar', 'مهندس اختبار (منتجات الذكاء الاصطناعي)', 'الاختبار والعمليات', NULL, NULL, 'اختبار المسارات الحرجة لمنتجات الذكاء الاصطناعي وتطبيقات الويب ومتعددة المنصات ومعالجة مخاطر الجودة حتى إغلاقها.'),
  ('modaleap-ai-gateway-operations-engineer', 'en', 'Gateway Operations Engineer', 'Testing & Ops', NULL, NULL, 'Run multi-channel LLM API access, quality probing, resource-pool scheduling and reliability.'),
  ('modaleap-ai-gateway-operations-engineer', 'zh', '网关运维工程师', '测试与运维', NULL, NULL, '负责大模型 API 多渠道接入、质量探测、资源池调度与稳定性保障。'),
  ('modaleap-ai-gateway-operations-engineer', 'ja', 'ゲートウェイ運用エンジニア', 'テスト・運用', NULL, NULL, '大規模モデル API のマルチチャネル接続、品質監視、リソースプールのスケジューリングと安定運用を担います。'),
  ('modaleap-ai-gateway-operations-engineer', 'ko', '게이트웨이 운영 엔지니어', '테스트·운영', NULL, NULL, '대규모 모델 API 멀티 채널 연동, 품질 모니터링, 리소스 풀 스케줄링과 안정성을 담당합니다.'),
  ('modaleap-ai-gateway-operations-engineer', 'es', 'Ingeniero de operaciones de gateway', 'Pruebas y operaciones', NULL, NULL, 'Gestiona el acceso multicanal a APIs de LLM, el sondeo de calidad, la planificación de recursos y la fiabilidad.'),
  ('modaleap-ai-gateway-operations-engineer', 'pt', 'Engenheiro de operações de gateway', 'Testes e operações', NULL, NULL, 'Gerencie o acesso multicanal a APIs de LLM, a sondagem de qualidade, o agendamento de recursos e a confiabilidade.'),
  ('modaleap-ai-gateway-operations-engineer', 'id', 'Engineer operasional gateway', 'Pengujian & operasional', NULL, NULL, 'Mengelola akses API LLM multikanal, pemantauan kualitas, penjadwalan resource pool, dan keandalan.'),
  ('modaleap-ai-gateway-operations-engineer', 'vi', 'Kỹ sư vận hành gateway', 'Kiểm thử & vận hành', NULL, NULL, 'Phụ trách kết nối API LLM đa kênh, giám sát chất lượng, điều phối tài nguyên và bảo đảm ổn định.'),
  ('modaleap-ai-gateway-operations-engineer', 'ar', 'مهندس عمليات البوابات', 'الاختبار والعمليات', NULL, NULL, 'إدارة الوصول متعدد القنوات إلى واجهات النماذج اللغوية الكبيرة، ورصد الجودة، وجدولة الموارد، وضمان الاستقرار.'),
  ('modaleap-delivery-operations-engineer', 'en', 'Delivery Operations Engineer', 'Solutions & Delivery', NULL, NULL, 'Deploy, inspect and support server hardware, Linux systems and on-site customer environments.'),
  ('modaleap-delivery-operations-engineer', 'zh', '交付运维工程师', '解决方案与交付', NULL, NULL, '负责服务器硬件、Linux 系统及客户现场的部署、巡检与运维支持。'),
  ('modaleap-delivery-operations-engineer', 'ja', '導入・運用エンジニア', 'ソリューション・導入', NULL, NULL, 'サーバーハードウェア、Linux、顧客現場の導入・点検・運用を支援します。'),
  ('modaleap-delivery-operations-engineer', 'ko', '딜리버리 운영 엔지니어', '솔루션·딜리버리', NULL, NULL, '서버 하드웨어, Linux 시스템, 고객 현장의 배포·점검·운영을 지원합니다.'),
  ('modaleap-delivery-operations-engineer', 'es', 'Ingeniero de operaciones de entrega', 'Soluciones y entrega', NULL, NULL, 'Despliega, revisa y da soporte a hardware de servidores, sistemas Linux y entornos del cliente.'),
  ('modaleap-delivery-operations-engineer', 'pt', 'Engenheiro de operações de entrega', 'Soluções e entrega', NULL, NULL, 'Implante, inspecione e dê suporte a hardware de servidores, sistemas Linux e ambientes do cliente.'),
  ('modaleap-delivery-operations-engineer', 'id', 'Engineer operasional delivery', 'Solusi & delivery', NULL, NULL, 'Menangani deployment, inspeksi, dan dukungan server, sistem Linux, serta lokasi pelanggan.'),
  ('modaleap-delivery-operations-engineer', 'vi', 'Kỹ sư vận hành triển khai', 'Giải pháp & triển khai', NULL, NULL, 'Triển khai, kiểm tra định kỳ và hỗ trợ vận hành phần cứng máy chủ, Linux và hệ thống tại khách hàng.'),
  ('modaleap-delivery-operations-engineer', 'ar', 'مهندس عمليات التسليم', 'الحلول والتسليم', NULL, NULL, 'نشر وفحص ودعم خوادم الأجهزة وأنظمة Linux وبيئات العملاء في مواقعهم.'),
  ('modaleap-ai-product-after-sales-lead', 'en', 'AI Product After-Sales Lead', 'Solutions & Delivery', NULL, NULL, 'Lead after-sales support for AI products: diagnose customer issues, close them out and feed insights back to product.'),
  ('modaleap-ai-product-after-sales-lead', 'zh', 'AI 产品售后负责人', '解决方案与交付', NULL, NULL, '负责 AI 产品的售后支持，推动客户问题定位、闭环与产品优化反馈。'),
  ('modaleap-ai-product-after-sales-lead', 'ja', 'AI プロダクト・アフターサポート責任者', 'ソリューション・導入', NULL, NULL, 'AI プロダクトのアフターサポートを統括し、顧客課題の特定・解決とプロダクト改善へのフィードバックを進めます。'),
  ('modaleap-ai-product-after-sales-lead', 'ko', 'AI 제품 사후지원 책임자', '솔루션·딜리버리', NULL, NULL, 'AI 제품 사후지원을 맡아 고객 문제를 파악·해결하고 제품 개선 피드백을 이끕니다.'),
  ('modaleap-ai-product-after-sales-lead', 'es', 'Responsable de posventa de productos de IA', 'Soluciones y entrega', NULL, NULL, 'Lidera el soporte posventa: diagnostica y resuelve incidencias y lleva el aprendizaje al producto.'),
  ('modaleap-ai-product-after-sales-lead', 'pt', 'Líder de pós-venda de produtos de IA', 'Soluções e entrega', NULL, NULL, 'Lidere o suporte pós-venda: diagnostique e resolva problemas e leve os aprendizados ao produto.'),
  ('modaleap-ai-product-after-sales-lead', 'id', 'Lead after-sales produk AI', 'Solusi & delivery', NULL, NULL, 'Memimpin dukungan purnajual produk AI: mendiagnosis masalah pelanggan, menuntaskannya, dan memberi masukan ke produk.'),
  ('modaleap-ai-product-after-sales-lead', 'vi', 'Trưởng nhóm hậu mãi sản phẩm AI', 'Giải pháp & triển khai', NULL, NULL, 'Phụ trách hậu mãi sản phẩm AI: xác định, xử lý dứt điểm vấn đề của khách hàng và phản hồi để cải tiến sản phẩm.'),
  ('modaleap-ai-product-after-sales-lead', 'ar', 'مسؤول خدمات ما بعد البيع لمنتجات الذكاء الاصطناعي', 'الحلول والتسليم', NULL, NULL, 'قيادة دعم ما بعد البيع: تشخيص مشكلات العملاء وحلها ونقل الملاحظات لتحسين المنتج.'),
  ('modaleap-ai-product-manager', 'en', 'AI Product Manager', 'Product & Operations', NULL, NULL, 'Design features, drive projects, analyze impact and research users for in-house AI products.'),
  ('modaleap-ai-product-manager', 'zh', 'AI 产品经理', '产品与运营', NULL, NULL, '参与公司自研 AI 产品的功能设计、项目推进、效果分析与用户洞察。'),
  ('modaleap-ai-product-manager', 'ja', 'AI プロダクトマネージャー', 'プロダクト・運営', NULL, NULL, '自社開発 AI プロダクトの機能設計、プロジェクト推進、効果分析、ユーザー理解に携わります。'),
  ('modaleap-ai-product-manager', 'ko', 'AI 프로덕트 매니저', '프로덕트·운영', NULL, NULL, '자체 개발 AI 제품의 기능 설계, 프로젝트 추진, 효과 분석, 사용자 인사이트 도출에 참여합니다.'),
  ('modaleap-ai-product-manager', 'es', 'Product manager de IA', 'Producto y operaciones', NULL, NULL, 'Diseña funciones, impulsa proyectos, analiza resultados e investiga usuarios de productos de IA propios.'),
  ('modaleap-ai-product-manager', 'pt', 'Gerente de produto de IA', 'Produto e operações', NULL, NULL, 'Projete funcionalidades, conduza projetos, analise resultados e pesquise usuários de produtos de IA próprios.'),
  ('modaleap-ai-product-manager', 'id', 'Product manager AI', 'Produk & operasional', NULL, NULL, 'Merancang fitur, menggerakkan proyek, menganalisis dampak, dan meriset pengguna produk AI internal.'),
  ('modaleap-ai-product-manager', 'vi', 'Quản lý sản phẩm AI', 'Sản phẩm & vận hành', NULL, NULL, 'Thiết kế tính năng, thúc đẩy dự án, phân tích hiệu quả và thấu hiểu người dùng cho sản phẩm AI tự phát triển.'),
  ('modaleap-ai-product-manager', 'ar', 'مدير منتجات الذكاء الاصطناعي', 'المنتج والعمليات', NULL, NULL, 'تصميم الميزات ودفع المشاريع وتحليل النتائج وفهم المستخدمين لمنتجات الذكاء الاصطناعي الداخلية.'),
  ('modaleap-content-operations', 'en', 'Content Operations', 'Product & Operations', NULL, NULL, 'Produce and run content across platforms: WeChat articles, hiring posts, social content and short-video scripts.'),
  ('modaleap-content-operations', 'zh', '内容运营', '产品与运营', NULL, NULL, '负责公众号、招聘图文、社交内容与短视频脚本等多平台内容生产和运营。'),
  ('modaleap-content-operations', 'ja', 'コンテンツ運営', 'プロダクト・運営', NULL, NULL, 'WeChat 公式アカウント、採用記事、SNS、ショート動画台本など多プラットフォームのコンテンツを制作・運営します。'),
  ('modaleap-content-operations', 'ko', '콘텐츠 운영', '프로덕트·운영', NULL, NULL, '위챗 공식 계정, 채용 콘텐츠, 소셜 콘텐츠, 숏폼 대본 등 멀티 플랫폼 콘텐츠를 제작·운영합니다.'),
  ('modaleap-content-operations', 'es', 'Operaciones de contenido', 'Producto y operaciones', NULL, NULL, 'Crea y gestiona contenido multiplataforma: artículos de WeChat, ofertas, redes sociales y guiones de video corto.'),
  ('modaleap-content-operations', 'pt', 'Operações de conteúdo', 'Produto e operações', NULL, NULL, 'Produza e gerencie conteúdo multiplataforma: artigos do WeChat, vagas, redes sociais e roteiros de vídeos curtos.'),
  ('modaleap-content-operations', 'id', 'Operasional konten', 'Produk & operasional', NULL, NULL, 'Memproduksi dan mengelola konten lintas platform: artikel WeChat, materi rekrutmen, media sosial, dan naskah video pendek.'),
  ('modaleap-content-operations', 'vi', 'Vận hành nội dung', 'Sản phẩm & vận hành', NULL, NULL, 'Sản xuất và vận hành nội dung đa nền tảng: bài WeChat, tin tuyển dụng, mạng xã hội và kịch bản video ngắn.'),
  ('modaleap-content-operations', 'ar', 'عمليات المحتوى', 'المنتج والعمليات', NULL, NULL, 'إنتاج المحتوى وإدارته عبر المنصات: مقالات WeChat ومنشورات التوظيف والمحتوى الاجتماعي ونصوص الفيديوهات القصيرة.'),
  ('modaleap-ecosystem-project-manager', 'en', 'Ecosystem Project Manager', 'Product & Operations', NULL, NULL, 'Own key ecosystem projects end to end, coordinating universities, industry bodies and communities.'),
  ('modaleap-ecosystem-project-manager', 'zh', '生态项目经理', '产品与运营', NULL, NULL, '独立负责重点生态项目，协调高校、行业机构与社区资源推动项目落地。'),
  ('modaleap-ecosystem-project-manager', 'ja', 'エコシステム・プロジェクトマネージャー', 'プロダクト・運営', NULL, NULL, '重点エコシステム案件を単独で担い、大学・業界団体・コミュニティと連携して実現します。'),
  ('modaleap-ecosystem-project-manager', 'ko', '생태계 프로젝트 매니저', '프로덕트·운영', NULL, NULL, '핵심 생태계 프로젝트를 독립적으로 맡아 대학, 업계 기관, 커뮤니티와 협력해 성과를 냅니다.'),
  ('modaleap-ecosystem-project-manager', 'es', 'Project manager de ecosistema', 'Producto y operaciones', NULL, NULL, 'Lidera proyectos clave de ecosistema coordinando universidades, organizaciones del sector y comunidades.'),
  ('modaleap-ecosystem-project-manager', 'pt', 'Gerente de projetos de ecossistema', 'Produto e operações', NULL, NULL, 'Lidere projetos-chave de ecossistema coordenando universidades, entidades do setor e comunidades.'),
  ('modaleap-ecosystem-project-manager', 'id', 'Project manager ekosistem', 'Produk & operasional', NULL, NULL, 'Memegang proyek ekosistem utama secara mandiri, berkoordinasi dengan kampus, lembaga industri, dan komunitas.'),
  ('modaleap-ecosystem-project-manager', 'vi', 'Quản lý dự án hệ sinh thái', 'Sản phẩm & vận hành', NULL, NULL, 'Độc lập phụ trách dự án hệ sinh thái trọng điểm, phối hợp trường đại học, tổ chức ngành và cộng đồng.'),
  ('modaleap-ecosystem-project-manager', 'ar', 'مدير مشاريع المنظومة', 'المنتج والعمليات', NULL, NULL, 'قيادة مشاريع المنظومة الرئيسية بالتنسيق مع الجامعات والجهات الصناعية والمجتمعات.'),
  ('modaleap-community-operations-intern', 'en', 'Community Operations Intern', 'Product & Operations', NULL, NULL, 'Run WeChat groups day to day: events, user tagging and feedback collection.'),
  ('modaleap-community-operations-intern', 'zh', '社群运营实习生', '产品与运营', NULL, NULL, '负责不同属性微信社群的日常运营、活动配合、用户标签与反馈收集。'),
  ('modaleap-community-operations-intern', 'ja', 'コミュニティ運営インターン', 'プロダクト・運営', NULL, NULL, '各種 WeChat グループの日常運営、イベント対応、ユーザータグ付け、フィードバック収集を担当します。'),
  ('modaleap-community-operations-intern', 'ko', '커뮤니티 운영 인턴', '프로덕트·운영', NULL, NULL, '다양한 위챗 커뮤니티의 일상 운영, 이벤트 지원, 사용자 태깅과 피드백 수집을 맡습니다.'),
  ('modaleap-community-operations-intern', 'es', 'Becario de gestión de comunidades', 'Producto y operaciones', NULL, NULL, 'Gestiona grupos de WeChat: actividades, etiquetado de usuarios y recogida de feedback.'),
  ('modaleap-community-operations-intern', 'pt', 'Estagiário de operações de comunidade', 'Produto e operações', NULL, NULL, 'Gerencie grupos do WeChat: atividades, marcação de usuários e coleta de feedback.'),
  ('modaleap-community-operations-intern', 'id', 'Magang operasional komunitas', 'Produk & operasional', NULL, NULL, 'Mengelola grup WeChat sehari-hari: acara, penandaan pengguna, dan pengumpulan masukan.'),
  ('modaleap-community-operations-intern', 'vi', 'Thực tập sinh vận hành cộng đồng', 'Sản phẩm & vận hành', NULL, NULL, 'Vận hành hằng ngày các nhóm WeChat: hỗ trợ sự kiện, gắn nhãn người dùng và thu thập phản hồi.'),
  ('modaleap-community-operations-intern', 'ar', 'متدرب عمليات المجتمع', 'المنتج والعمليات', NULL, NULL, 'إدارة مجموعات WeChat يوميًا: الفعاليات وتصنيف المستخدمين وجمع الملاحظات.'),
  ('modaleap-sales-manager', 'en', 'Sales Manager', 'Marketing & Sales', NULL, NULL, 'Sell the Leap product line to government, state-owned enterprises and industry customers, and grow channels.'),
  ('modaleap-sales-manager', 'zh', '销售经理', '市场与销售', NULL, NULL, '负责 Leap 系列产品面向党政、央国企及行业客户的销售与渠道拓展。'),
  ('modaleap-sales-manager', 'ja', '営業マネージャー', 'マーケティング・営業', NULL, NULL, 'Leap シリーズを政府機関・国有企業・業界顧客へ販売し、チャネルを開拓します。'),
  ('modaleap-sales-manager', 'ko', '영업 매니저', '마케팅·영업', NULL, NULL, 'Leap 시리즈 제품을 정부·국유기업·산업 고객에게 판매하고 채널을 확장합니다.'),
  ('modaleap-sales-manager', 'es', 'Gerente de ventas', 'Marketing y ventas', NULL, NULL, 'Vende la línea Leap a gobierno, empresas estatales y clientes sectoriales, y desarrolla canales.'),
  ('modaleap-sales-manager', 'pt', 'Gerente de vendas', 'Marketing e vendas', NULL, NULL, 'Venda a linha Leap para governo, estatais e clientes setoriais e desenvolva canais.'),
  ('modaleap-sales-manager', 'id', 'Manajer penjualan', 'Pemasaran & penjualan', NULL, NULL, 'Menjual lini produk Leap ke pemerintah, BUMN, dan pelanggan industri, serta mengembangkan kanal.'),
  ('modaleap-sales-manager', 'vi', 'Quản lý kinh doanh', 'Marketing & bán hàng', NULL, NULL, 'Bán dòng sản phẩm Leap cho khối chính phủ, doanh nghiệp nhà nước và khách hàng ngành, đồng thời mở rộng kênh.'),
  ('modaleap-sales-manager', 'ar', 'مدير المبيعات', 'التسويق والمبيعات', NULL, NULL, 'بيع منتجات سلسلة Leap للجهات الحكومية والشركات المملوكة للدولة وعملاء القطاعات وتوسيع القنوات.'),
  ('modaleap-sales-management-trainee', 'en', 'Sales Management Trainee', 'Marketing & Sales', NULL, NULL, 'Support business documents, bid preparation, client visits and follow-ups after negotiations.'),
  ('modaleap-sales-management-trainee', 'zh', '销售部管培生', '市场与销售', NULL, NULL, '支持商务文件、招投标准备、客户接待与洽谈后的事项跟进。'),
  ('modaleap-sales-management-trainee', 'ja', '営業部マネジメントトレーニー', 'マーケティング・営業', NULL, NULL, '商務文書、入札準備、顧客対応、商談後のフォローアップを支援します。'),
  ('modaleap-sales-management-trainee', 'ko', '영업부 관리 연수생', '마케팅·영업', NULL, NULL, '비즈니스 문서, 입찰 준비, 고객 응대 및 협상 후속 업무를 지원합니다.'),
  ('modaleap-sales-management-trainee', 'es', 'Trainee de gestión comercial', 'Marketing y ventas', NULL, NULL, 'Apoya documentación comercial, preparación de licitaciones, atención a clientes y seguimiento.'),
  ('modaleap-sales-management-trainee', 'pt', 'Trainee de gestão comercial', 'Marketing e vendas', NULL, NULL, 'Apoie documentos comerciais, preparação de licitações, atendimento a clientes e acompanhamento.'),
  ('modaleap-sales-management-trainee', 'id', 'Management trainee penjualan', 'Pemasaran & penjualan', NULL, NULL, 'Mendukung dokumen bisnis, persiapan tender, penerimaan klien, dan tindak lanjut negosiasi.'),
  ('modaleap-sales-management-trainee', 'vi', 'Quản trị viên tập sự khối kinh doanh', 'Marketing & bán hàng', NULL, NULL, 'Hỗ trợ hồ sơ thương mại, chuẩn bị đấu thầu, tiếp khách và theo dõi sau đàm phán.'),
  ('modaleap-sales-management-trainee', 'ar', 'متدرب إداري في المبيعات', 'التسويق والمبيعات', NULL, NULL, 'دعم المستندات التجارية وتحضير المناقصات واستقبال العملاء ومتابعة ما بعد التفاوض.'),
  ('modaleap-channel-development', 'en', 'Channel Development', 'Marketing & Sales', NULL, NULL, 'Recruit regional distributors and agents; own channel signings, collections and coverage.'),
  ('modaleap-channel-development', 'zh', '渠道拓展', '市场与销售', NULL, NULL, '开拓区域经销商与代理商，对渠道签约、回款和覆盖率负责。'),
  ('modaleap-channel-development', 'ja', 'チャネル開拓', 'マーケティング・営業', NULL, NULL, '地域の販売店・代理店を開拓し、チャネル契約・回収・カバー率に責任を持ちます。'),
  ('modaleap-channel-development', 'ko', '채널 개척', '마케팅·영업', NULL, NULL, '지역 대리점과 에이전트를 개척하고 채널 계약, 수금, 커버리지를 책임집니다.'),
  ('modaleap-channel-development', 'es', 'Desarrollo de canales', 'Marketing y ventas', NULL, NULL, 'Capta distribuidores y agentes regionales; responde por contratos, cobros y cobertura.'),
  ('modaleap-channel-development', 'pt', 'Desenvolvimento de canais', 'Marketing e vendas', NULL, NULL, 'Conquiste distribuidores e agentes regionais; responda por contratos, recebimentos e cobertura.'),
  ('modaleap-channel-development', 'id', 'Pengembangan kanal', 'Pemasaran & penjualan', NULL, NULL, 'Merekrut distributor dan agen regional; bertanggung jawab atas kontrak, penagihan, dan cakupan kanal.'),
  ('modaleap-channel-development', 'vi', 'Phát triển kênh', 'Marketing & bán hàng', NULL, NULL, 'Mở rộng nhà phân phối và đại lý khu vực; chịu trách nhiệm ký kết, thu hồi công nợ và độ phủ kênh.'),
  ('modaleap-channel-development', 'ar', 'تطوير القنوات', 'التسويق والمبيعات', NULL, NULL, 'استقطاب الموزعين والوكلاء الإقليميين وتحمل مسؤولية التعاقد والتحصيل والتغطية.'),
  ('modaleap-channel-business-manager', 'en', 'Channel & Business Manager', 'Marketing & Sales', NULL, NULL, 'Coordinate channel contracts, shipping, receivables, bids and distributor management for steady channel output.'),
  ('modaleap-channel-business-manager', 'zh', '渠道管理 & 商务经理', '市场与销售', NULL, NULL, '统筹渠道合同、发货、应收、招投标与经销商管理，保障渠道稳定产出。'),
  ('modaleap-channel-business-manager', 'ja', 'チャネル管理・ビジネスマネージャー', 'マーケティング・営業', NULL, NULL, 'チャネル契約、出荷、売掛金、入札、販売店管理を統括し、安定した成果を支えます。'),
  ('modaleap-channel-business-manager', 'ko', '채널 관리 & 비즈니스 매니저', '마케팅·영업', NULL, NULL, '채널 계약, 출고, 매출채권, 입찰, 대리점 관리를 총괄해 안정적인 성과를 보장합니다.'),
  ('modaleap-channel-business-manager', 'es', 'Gerente de canales y negocio', 'Marketing y ventas', NULL, NULL, 'Coordina contratos, envíos, cobros, licitaciones y distribuidores para un canal estable.'),
  ('modaleap-channel-business-manager', 'pt', 'Gerente de canais e negócios', 'Marketing e vendas', NULL, NULL, 'Coordene contratos, envios, recebíveis, licitações e distribuidores para um canal estável.'),
  ('modaleap-channel-business-manager', 'id', 'Manajer kanal & bisnis', 'Pemasaran & penjualan', NULL, NULL, 'Mengoordinasikan kontrak kanal, pengiriman, piutang, tender, dan manajemen distributor.'),
  ('modaleap-channel-business-manager', 'vi', 'Quản lý kênh & thương mại', 'Marketing & bán hàng', NULL, NULL, 'Điều phối hợp đồng kênh, giao hàng, công nợ, đấu thầu và quản lý nhà phân phối để kênh vận hành ổn định.'),
  ('modaleap-channel-business-manager', 'ar', 'مدير القنوات والأعمال', 'التسويق والمبيعات', NULL, NULL, 'تنسيق عقود القنوات والشحن والمستحقات والمناقصات وإدارة الموزعين لضمان إنتاج مستقر.'),
  ('modaleap-hr-specialist', 'en', 'HR Specialist', 'Corporate Functions', NULL, NULL, 'Run the full recruiting cycle and core HR operations, and keep improving employee support and people processes.'),
  ('modaleap-hr-specialist', 'zh', 'HR 专员', '职能类', NULL, NULL, '承担招聘全流程及基础人事运营，持续优化员工支持与人力流程。'),
  ('modaleap-hr-specialist', 'ja', '人事担当', 'コーポレート部門', NULL, NULL, '採用の全工程と基本的な人事業務を担い、従業員支援と人事プロセスを改善し続けます。'),
  ('modaleap-hr-specialist', 'ko', 'HR 담당자', '경영지원', NULL, NULL, '채용 전 과정과 기본 인사 운영을 맡고 직원 지원 및 인사 프로세스를 지속적으로 개선합니다.'),
  ('modaleap-hr-specialist', 'es', 'Especialista de RR. HH.', 'Funciones corporativas', NULL, NULL, 'Gestiona todo el ciclo de selección y las operaciones de RR. HH., mejorando procesos y apoyo al equipo.'),
  ('modaleap-hr-specialist', 'pt', 'Especialista de RH', 'Funções corporativas', NULL, NULL, 'Conduza todo o ciclo de recrutamento e as operações de RH, melhorando processos e o apoio ao time.'),
  ('modaleap-hr-specialist', 'id', 'Spesialis HR', 'Fungsi korporat', NULL, NULL, 'Menjalankan siklus rekrutmen penuh dan operasional HR dasar, serta terus memperbaiki proses SDM.'),
  ('modaleap-hr-specialist', 'vi', 'Chuyên viên nhân sự', 'Khối chức năng', NULL, NULL, 'Đảm nhận toàn bộ quy trình tuyển dụng và vận hành nhân sự cơ bản, liên tục cải thiện quy trình.'),
  ('modaleap-hr-specialist', 'ar', 'أخصائي موارد بشرية', 'الوظائف المؤسسية', NULL, NULL, 'إدارة دورة التوظيف كاملة وعمليات الموارد البشرية الأساسية وتحسين دعم الموظفين والإجراءات باستمرار.'),
  ('modaleap-finance-assistant', 'en', 'Finance Assistant', 'Corporate Functions', NULL, NULL, 'Handle daily cash, documents, receivables and payables, basic bookkeeping and tax, and finance records.'),
  ('modaleap-finance-assistant', 'zh', '财务助理', '职能类', NULL, NULL, '负责日常资金、单据、往来账、基础账税及财务资料归档。'),
  ('modaleap-finance-assistant', 'ja', '経理アシスタント', 'コーポレート部門', NULL, NULL, '日々の資金、伝票、債権債務、基本的な記帳・税務、財務資料の保管を担当します。'),
  ('modaleap-finance-assistant', 'ko', '재무 어시스턴트', '경영지원', NULL, NULL, '일상 자금, 증빙, 채권·채무, 기본 회계·세무, 재무 자료 보관을 담당합니다.'),
  ('modaleap-finance-assistant', 'es', 'Asistente de finanzas', 'Funciones corporativas', NULL, NULL, 'Gestiona tesorería diaria, documentos, cuentas por cobrar y pagar, contabilidad básica e impuestos.'),
  ('modaleap-finance-assistant', 'pt', 'Assistente financeiro', 'Funções corporativas', NULL, NULL, 'Cuide do caixa diário, documentos, contas a receber e a pagar, contabilidade básica e impostos.'),
  ('modaleap-finance-assistant', 'id', 'Asisten keuangan', 'Fungsi korporat', NULL, NULL, 'Mengelola kas harian, dokumen, piutang-utang, pembukuan dan pajak dasar, serta arsip keuangan.'),
  ('modaleap-finance-assistant', 'vi', 'Trợ lý tài chính', 'Khối chức năng', NULL, NULL, 'Phụ trách quỹ hằng ngày, chứng từ, công nợ, sổ sách thuế cơ bản và lưu trữ hồ sơ tài chính.'),
  ('modaleap-finance-assistant', 'ar', 'مساعد مالي', 'الوظائف المؤسسية', NULL, NULL, 'إدارة النقد اليومي والمستندات والذمم المدينة والدائنة والمحاسبة والضرائب الأساسية وأرشفة السجلات.'),
  ('modaleap-general-office-intern', 'en', 'General Office Assistant Intern', 'Corporate Functions', NULL, NULL, 'Help drive digitalization projects, AI applications, cross-team matters and IP work.'),
  ('modaleap-general-office-intern', 'zh', '总经办助理实习', '职能类', NULL, NULL, '协助推进数字化项目、AI 业务应用、跨部门事项与知识产权工作。'),
  ('modaleap-general-office-intern', 'ja', '社長室アシスタント・インターン', 'コーポレート部門', NULL, NULL, 'DX プロジェクト、AI 活用、部門横断の案件、知財業務の推進を支援します。'),
  ('modaleap-general-office-intern', 'ko', '대표이사실 어시스턴트 인턴', '경영지원', NULL, NULL, '디지털화 프로젝트, AI 업무 적용, 부서 간 협업, 지식재산 업무를 지원합니다.'),
  ('modaleap-general-office-intern', 'es', 'Becario de asistente de dirección general', 'Funciones corporativas', NULL, NULL, 'Apoya proyectos de digitalización, aplicaciones de IA, temas transversales y propiedad intelectual.'),
  ('modaleap-general-office-intern', 'pt', 'Estagiário de assistente da diretoria', 'Funções corporativas', NULL, NULL, 'Apoie projetos de digitalização, aplicações de IA, temas entre áreas e propriedade intelectual.'),
  ('modaleap-general-office-intern', 'id', 'Magang asisten kantor direksi', 'Fungsi korporat', NULL, NULL, 'Membantu proyek digitalisasi, penerapan AI, urusan lintas tim, dan kekayaan intelektual.'),
  ('modaleap-general-office-intern', 'vi', 'Thực tập trợ lý văn phòng tổng giám đốc', 'Khối chức năng', NULL, NULL, 'Hỗ trợ dự án số hóa, ứng dụng AI, công việc liên phòng ban và sở hữu trí tuệ.'),
  ('modaleap-general-office-intern', 'ar', 'متدرب مساعد في مكتب الإدارة العامة', 'الوظائف المؤسسية', NULL, NULL, 'المساعدة في مشاريع التحول الرقمي وتطبيقات الذكاء الاصطناعي والمهام المشتركة بين الفرق والملكية الفكرية.'),
  ('modaleap-coo-business-assistant', 'en', 'COO Business Assistant', 'Corporate Functions', NULL, NULL, 'Help the COO with internal and external coordination, information flow and closing out key tasks.'),
  ('modaleap-coo-business-assistant', 'zh', 'COO 业务助理', '职能类', NULL, NULL, '协助 COO 完成内外部业务协同、信息传递与重点任务闭环。'),
  ('modaleap-coo-business-assistant', 'ja', 'COO ビジネスアシスタント', 'コーポレート部門', NULL, NULL, 'COO の社内外調整、情報伝達、重点タスクの完遂をサポートします。'),
  ('modaleap-coo-business-assistant', 'ko', 'COO 비즈니스 어시스턴트', '경영지원', NULL, NULL, 'COO의 내외부 업무 협업, 정보 전달, 핵심 과제 마무리를 지원합니다.'),
  ('modaleap-coo-business-assistant', 'es', 'Asistente de negocio del COO', 'Funciones corporativas', NULL, NULL, 'Apoya al COO en coordinación interna y externa, flujo de información y cierre de tareas clave.'),
  ('modaleap-coo-business-assistant', 'pt', 'Assistente de negócios do COO', 'Funções corporativas', NULL, NULL, 'Apoie o COO na coordenação interna e externa, no fluxo de informações e na conclusão de tarefas-chave.'),
  ('modaleap-coo-business-assistant', 'id', 'Asisten bisnis COO', 'Fungsi korporat', NULL, NULL, 'Membantu COO dalam koordinasi internal-eksternal, alur informasi, dan penuntasan tugas penting.'),
  ('modaleap-coo-business-assistant', 'vi', 'Trợ lý kinh doanh COO', 'Khối chức năng', NULL, NULL, 'Hỗ trợ COO phối hợp công việc trong và ngoài, truyền đạt thông tin và hoàn tất nhiệm vụ trọng điểm.'),
  ('modaleap-coo-business-assistant', 'ar', 'مساعد أعمال الرئيس التنفيذي للعمليات', 'الوظائف المؤسسية', NULL, NULL, 'مساعدة الرئيس التنفيذي للعمليات في التنسيق الداخلي والخارجي ونقل المعلومات وإنجاز المهام الرئيسية.'),
  ('modaleap-ai-supply-chain-manager', 'en', 'AI Supply Chain Manager', 'Corporate Functions', NULL, NULL, 'Own procurement of compute, cloud, APIs and SaaS, plus supplier management and inventory strategy.'),
  ('modaleap-ai-supply-chain-manager', 'zh', 'AI 供应链经理', '职能类', NULL, NULL, '统筹算力、云资源、API 与 SaaS 等全品类采购、供应商管理与库存策略。'),
  ('modaleap-ai-supply-chain-manager', 'ja', 'AI サプライチェーンマネージャー', 'コーポレート部門', NULL, NULL, '計算資源、クラウド、API、SaaS の調達、サプライヤー管理、在庫戦略を統括します。'),
  ('modaleap-ai-supply-chain-manager', 'ko', 'AI 공급망 매니저', '경영지원', NULL, NULL, '컴퓨팅, 클라우드, API, SaaS 전 품목 구매와 공급사 관리, 재고 전략을 총괄합니다.'),
  ('modaleap-ai-supply-chain-manager', 'es', 'Gerente de cadena de suministro de IA', 'Funciones corporativas', NULL, NULL, 'Gestiona la compra de cómputo, nube, APIs y SaaS, proveedores y estrategia de inventario.'),
  ('modaleap-ai-supply-chain-manager', 'pt', 'Gerente de cadeia de suprimentos de IA', 'Funções corporativas', NULL, NULL, 'Gerencie compras de computação, nuvem, APIs e SaaS, fornecedores e estratégia de estoque.'),
  ('modaleap-ai-supply-chain-manager', 'id', 'Manajer rantai pasok AI', 'Fungsi korporat', NULL, NULL, 'Mengelola pengadaan komputasi, cloud, API, dan SaaS, manajemen pemasok, serta strategi inventaris.'),
  ('modaleap-ai-supply-chain-manager', 'vi', 'Quản lý chuỗi cung ứng AI', 'Khối chức năng', NULL, NULL, 'Điều phối mua sắm năng lực tính toán, đám mây, API và SaaS, quản lý nhà cung cấp và chiến lược tồn kho.'),
  ('modaleap-ai-supply-chain-manager', 'ar', 'مدير سلسلة توريد الذكاء الاصطناعي', 'الوظائف المؤسسية', NULL, NULL, 'الإشراف على شراء الحوسبة والسحابة وواجهات البرمجة وSaaS وإدارة الموردين واستراتيجية المخزون.'),
  ('modaleap-training-instructor', 'en', 'Training Instructor', 'Corporate Functions', NULL, NULL, 'Build customer and internal training programs and teach Agent platform and hands-on courses.'),
  ('modaleap-training-instructor', 'zh', '培训讲师', '职能类', NULL, NULL, '建设客户与内部培训体系，讲授 Agent 平台和实操课程。'),
  ('modaleap-training-instructor', 'ja', '研修講師', 'コーポレート部門', NULL, NULL, '顧客向け・社内向けの研修体系を作り、Agent プラットフォームや実践講座を担当します。'),
  ('modaleap-training-instructor', 'ko', '교육 강사', '경영지원', NULL, NULL, '고객 및 내부 교육 체계를 구축하고 Agent 플랫폼과 실습 과정을 강의합니다.'),
  ('modaleap-training-instructor', 'es', 'Formador', 'Funciones corporativas', NULL, NULL, 'Crea programas de formación para clientes y equipo, e imparte cursos de la plataforma Agent.'),
  ('modaleap-training-instructor', 'pt', 'Instrutor de treinamento', 'Funções corporativas', NULL, NULL, 'Crie programas de treinamento para clientes e equipe e ministre cursos da plataforma Agent.'),
  ('modaleap-training-instructor', 'id', 'Instruktur pelatihan', 'Fungsi korporat', NULL, NULL, 'Membangun program pelatihan pelanggan dan internal serta mengajar kursus platform Agent.'),
  ('modaleap-training-instructor', 'vi', 'Giảng viên đào tạo', 'Khối chức năng', NULL, NULL, 'Xây dựng hệ thống đào tạo cho khách hàng và nội bộ, giảng dạy nền tảng Agent và khóa thực hành.'),
  ('modaleap-training-instructor', 'ar', 'مدرب', 'الوظائف المؤسسية', NULL, NULL, 'بناء برامج تدريب للعملاء والموظفين وتقديم دورات منصة الوكلاء والتطبيق العملي.'),
  ('modaleap-visual-designer-part-time', 'en', 'Visual Designer (Part-time)', 'Design', NULL, NULL, 'Support brand, event, packaging and basic UI design on a part-time basis.'),
  ('modaleap-visual-designer-part-time', 'zh', '美工设计兼职', '设计类', NULL, NULL, '以兼职方式支持公司品牌、活动、产品包装与基础界面设计。'),
  ('modaleap-visual-designer-part-time', 'ja', 'ビジュアルデザイナー（副業）', 'デザイン', NULL, NULL, 'ブランド、イベント、パッケージ、基本的な UI デザインを副業として支援します。'),
  ('modaleap-visual-designer-part-time', 'ko', '비주얼 디자이너 (파트타임)', '디자인', NULL, NULL, '브랜드, 행사, 제품 패키지, 기본 UI 디자인을 파트타임으로 지원합니다.'),
  ('modaleap-visual-designer-part-time', 'es', 'Diseñador visual (media jornada)', 'Diseño', NULL, NULL, 'Apoya a tiempo parcial el diseño de marca, eventos, empaques e interfaces básicas.'),
  ('modaleap-visual-designer-part-time', 'pt', 'Designer visual (meio período)', 'Design', NULL, NULL, 'Apoie em meio período o design de marca, eventos, embalagens e interfaces básicas.'),
  ('modaleap-visual-designer-part-time', 'id', 'Desainer visual (paruh waktu)', 'Desain', NULL, NULL, 'Mendukung desain merek, acara, kemasan produk, dan UI dasar secara paruh waktu.'),
  ('modaleap-visual-designer-part-time', 'vi', 'Thiết kế đồ họa (bán thời gian)', 'Thiết kế', NULL, NULL, 'Hỗ trợ bán thời gian thiết kế thương hiệu, sự kiện, bao bì và giao diện cơ bản.'),
  ('modaleap-visual-designer-part-time', 'ar', 'مصمم بصري (دوام جزئي)', 'التصميم', NULL, NULL, 'دعم تصميم الهوية والفعاليات والتغليف والواجهات الأساسية بدوام جزئي.'),
  ('deepseek-8d40c764', 'en', 'Agent Harness Team', 'Full-stack / Algorithms', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-8d40c764', 'zh', 'Agent Harness 团队', '全栈开发/算法', '北京、杭州', NULL, NULL),
  ('deepseek-8d40c764', 'ja', 'Agent Harness チーム', 'フルスタック / アルゴリズム', '北京・杭州', NULL, NULL),
  ('deepseek-8d40c764', 'ko', 'Agent Harness 팀', '풀스택 / 알고리즘', '베이징 · 항저우', NULL, NULL),
  ('deepseek-8d40c764', 'es', 'Equipo Agent Harness', 'Full-stack / Algoritmos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-8d40c764', 'pt', 'Equipe Agent Harness', 'Full-stack / Algoritmos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-8d40c764', 'id', 'Tim Agent Harness', 'Full-stack / Algoritma', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-8d40c764', 'vi', 'Nhóm Agent Harness', 'Full-stack / Thuật toán', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-8d40c764', 'ar', 'فريق Agent Harness', 'تطوير متكامل / خوارزميات', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-43f8551a', 'en', 'LLM Training / Inference Framework Engineer', 'AI Core Systems', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-43f8551a', 'zh', '大模型训练/推理框架工程师', 'AI 核心系统研发', '北京、杭州', NULL, NULL),
  ('deepseek-43f8551a', 'ja', '大規模モデル学習・推論フレームワークエンジニア', 'AI コアシステム開発', '北京・杭州', NULL, NULL),
  ('deepseek-43f8551a', 'ko', '대규모 모델 학습/추론 프레임워크 엔지니어', 'AI 핵심 시스템 개발', '베이징 · 항저우', NULL, NULL),
  ('deepseek-43f8551a', 'es', 'Ingeniero de frameworks de entrenamiento / inferencia de LLM', 'Sistemas núcleo de IA', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-43f8551a', 'pt', 'Engenheiro de frameworks de treinamento / inferência de LLM', 'Sistemas centrais de IA', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-43f8551a', 'id', 'Engineer framework training / inferensi LLM', 'Sistem inti AI', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-43f8551a', 'vi', 'Kỹ sư framework huấn luyện / suy luận LLM', 'Hệ thống lõi AI', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-43f8551a', 'ar', 'مهندس أطر تدريب / استدلال النماذج اللغوية الكبيرة', 'أنظمة الذكاء الاصطناعي الأساسية', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-2eb2e75d', 'en', 'Backend Engineer', 'Full-stack / Algorithms', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-2eb2e75d', 'zh', '服务端开发工程师', '全栈开发/算法', '北京、杭州', NULL, NULL),
  ('deepseek-2eb2e75d', 'ja', 'サーバーサイドエンジニア', 'フルスタック / アルゴリズム', '北京・杭州', NULL, NULL),
  ('deepseek-2eb2e75d', 'ko', '백엔드 개발 엔지니어', '풀스택 / 알고리즘', '베이징 · 항저우', NULL, NULL),
  ('deepseek-2eb2e75d', 'es', 'Ingeniero backend', 'Full-stack / Algoritmos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-2eb2e75d', 'pt', 'Engenheiro de back-end', 'Full-stack / Algoritmos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-2eb2e75d', 'id', 'Backend engineer', 'Full-stack / Algoritma', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-2eb2e75d', 'vi', 'Kỹ sư backend', 'Full-stack / Thuật toán', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-2eb2e75d', 'ar', 'مهندس واجهات خلفية', 'تطوير متكامل / خوارزميات', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-bae809fb', 'en', 'Agent Elastic Compute Engineer', 'Full-stack / Algorithms', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-bae809fb', 'zh', 'Agent 弹性计算研发工程师', '全栈开发/算法', '北京、杭州', NULL, NULL),
  ('deepseek-bae809fb', 'ja', 'Agent エラスティックコンピューティングエンジニア', 'フルスタック / アルゴリズム', '北京・杭州', NULL, NULL),
  ('deepseek-bae809fb', 'ko', 'Agent 탄력적 컴퓨팅 개발 엔지니어', '풀스택 / 알고리즘', '베이징 · 항저우', NULL, NULL),
  ('deepseek-bae809fb', 'es', 'Ingeniero de cómputo elástico para agentes', 'Full-stack / Algoritmos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-bae809fb', 'pt', 'Engenheiro de computação elástica para agentes', 'Full-stack / Algoritmos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-bae809fb', 'id', 'Engineer komputasi elastis Agent', 'Full-stack / Algoritma', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-bae809fb', 'vi', 'Kỹ sư điện toán co giãn cho Agent', 'Full-stack / Thuật toán', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-bae809fb', 'ar', 'مهندس الحوسبة المرنة للوكلاء', 'تطوير متكامل / خوارزميات', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-01416da2', 'en', 'Deep Learning Engineer', 'Full-stack / Algorithms', 'Beijing', NULL, NULL),
  ('deepseek-01416da2', 'zh', '深度学习研发工程师', '全栈开发/算法', '北京', NULL, NULL),
  ('deepseek-01416da2', 'ja', '深層学習エンジニア', 'フルスタック / アルゴリズム', '北京', NULL, NULL),
  ('deepseek-01416da2', 'ko', '딥러닝 개발 엔지니어', '풀스택 / 알고리즘', '베이징', NULL, NULL),
  ('deepseek-01416da2', 'es', 'Ingeniero de deep learning', 'Full-stack / Algoritmos', 'Pekín', NULL, NULL),
  ('deepseek-01416da2', 'pt', 'Engenheiro de deep learning', 'Full-stack / Algoritmos', 'Pequim', NULL, NULL),
  ('deepseek-01416da2', 'id', 'Engineer deep learning', 'Full-stack / Algoritma', 'Beijing', NULL, NULL),
  ('deepseek-01416da2', 'vi', 'Kỹ sư học sâu', 'Full-stack / Thuật toán', 'Bắc Kinh', NULL, NULL),
  ('deepseek-01416da2', 'ar', 'مهندس التعلم العميق', 'تطوير متكامل / خوارزميات', 'بكين', NULL, NULL),
  ('deepseek-8a4c2868', 'en', 'Pre-training Data Engineer', 'Full-stack / Algorithms', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-8a4c2868', 'zh', '预训练数据工程师', '全栈开发/算法', '北京、杭州', NULL, NULL),
  ('deepseek-8a4c2868', 'ja', '事前学習データエンジニア', 'フルスタック / アルゴリズム', '北京・杭州', NULL, NULL),
  ('deepseek-8a4c2868', 'ko', '사전학습 데이터 엔지니어', '풀스택 / 알고리즘', '베이징 · 항저우', NULL, NULL),
  ('deepseek-8a4c2868', 'es', 'Ingeniero de datos de preentrenamiento', 'Full-stack / Algoritmos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-8a4c2868', 'pt', 'Engenheiro de dados de pré-treinamento', 'Full-stack / Algoritmos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-8a4c2868', 'id', 'Engineer data pre-training', 'Full-stack / Algoritma', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-8a4c2868', 'vi', 'Kỹ sư dữ liệu tiền huấn luyện', 'Full-stack / Thuật toán', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-8a4c2868', 'ar', 'مهندس بيانات التدريب المسبق', 'تطوير متكامل / خوارزميات', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-1df4597d', 'en', 'AI Search Algorithm / Architecture Engineer', 'Full-stack / Algorithms', 'Beijing', NULL, NULL),
  ('deepseek-1df4597d', 'zh', 'AI 搜索算法 / 架构工程师', '全栈开发/算法', '北京', NULL, NULL),
  ('deepseek-1df4597d', 'ja', 'AI 検索アルゴリズム / アーキテクチャエンジニア', 'フルスタック / アルゴリズム', '北京', NULL, NULL),
  ('deepseek-1df4597d', 'ko', 'AI 검색 알고리즘 / 아키텍처 엔지니어', '풀스택 / 알고리즘', '베이징', NULL, NULL),
  ('deepseek-1df4597d', 'es', 'Ingeniero de algoritmos / arquitectura de búsqueda con IA', 'Full-stack / Algoritmos', 'Pekín', NULL, NULL),
  ('deepseek-1df4597d', 'pt', 'Engenheiro de algoritmos / arquitetura de busca com IA', 'Full-stack / Algoritmos', 'Pequim', NULL, NULL),
  ('deepseek-1df4597d', 'id', 'Engineer algoritma / arsitektur pencarian AI', 'Full-stack / Algoritma', 'Beijing', NULL, NULL),
  ('deepseek-1df4597d', 'vi', 'Kỹ sư thuật toán / kiến trúc tìm kiếm AI', 'Full-stack / Thuật toán', 'Bắc Kinh', NULL, NULL),
  ('deepseek-1df4597d', 'ar', 'مهندس خوارزميات / معمارية البحث بالذكاء الاصطناعي', 'تطوير متكامل / خوارزميات', 'بكين', NULL, NULL),
  ('deepseek-0a317cbb', 'en', 'Frontend / Client Engineer', 'Full-stack / Algorithms', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-0a317cbb', 'zh', '前端 / 客户端开发工程师', '全栈开发/算法', '北京、杭州', NULL, NULL),
  ('deepseek-0a317cbb', 'ja', 'フロントエンド / クライアントエンジニア', 'フルスタック / アルゴリズム', '北京・杭州', NULL, NULL),
  ('deepseek-0a317cbb', 'ko', '프론트엔드 / 클라이언트 개발 엔지니어', '풀스택 / 알고리즘', '베이징 · 항저우', NULL, NULL),
  ('deepseek-0a317cbb', 'es', 'Ingeniero frontend / cliente', 'Full-stack / Algoritmos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-0a317cbb', 'pt', 'Engenheiro de front-end / cliente', 'Full-stack / Algoritmos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-0a317cbb', 'id', 'Engineer frontend / klien', 'Full-stack / Algoritma', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-0a317cbb', 'vi', 'Kỹ sư frontend / client', 'Full-stack / Thuật toán', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-0a317cbb', 'ar', 'مهندس واجهات أمامية / تطبيقات العميل', 'تطوير متكامل / خوارزميات', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-50733e68', 'en', 'Software Engineer in Test', 'Full-stack / Algorithms', 'Hangzhou', NULL, NULL),
  ('deepseek-50733e68', 'zh', '测试开发工程师', '全栈开发/算法', '杭州', NULL, NULL),
  ('deepseek-50733e68', 'ja', 'テスト開発エンジニア', 'フルスタック / アルゴリズム', '杭州', NULL, NULL),
  ('deepseek-50733e68', 'ko', '테스트 개발 엔지니어', '풀스택 / 알고리즘', '항저우', NULL, NULL),
  ('deepseek-50733e68', 'es', 'Ingeniero de desarrollo de pruebas', 'Full-stack / Algoritmos', 'Hangzhou', NULL, NULL),
  ('deepseek-50733e68', 'pt', 'Engenheiro de desenvolvimento de testes', 'Full-stack / Algoritmos', 'Hangzhou', NULL, NULL),
  ('deepseek-50733e68', 'id', 'Engineer pengembangan pengujian', 'Full-stack / Algoritma', 'Hangzhou', NULL, NULL),
  ('deepseek-50733e68', 'vi', 'Kỹ sư phát triển kiểm thử', 'Full-stack / Thuật toán', 'Hàng Châu', NULL, NULL),
  ('deepseek-50733e68', 'ar', 'مهندس تطوير الاختبارات', 'تطوير متكامل / خوارزميات', 'هانغتشو', NULL, NULL),
  ('deepseek-efc2a5d0', 'en', 'Cross-disciplinary AI Talent', 'Full-stack / Algorithms', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-efc2a5d0', 'zh', 'AI 跨界技术人才', '全栈开发/算法', '北京、杭州', NULL, NULL),
  ('deepseek-efc2a5d0', 'ja', 'AI 分野横断型技術人材', 'フルスタック / アルゴリズム', '北京・杭州', NULL, NULL),
  ('deepseek-efc2a5d0', 'ko', 'AI 융합 기술 인재', '풀스택 / 알고리즘', '베이징 · 항저우', NULL, NULL),
  ('deepseek-efc2a5d0', 'es', 'Talento técnico interdisciplinar en IA', 'Full-stack / Algoritmos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-efc2a5d0', 'pt', 'Talento técnico interdisciplinar em IA', 'Full-stack / Algoritmos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-efc2a5d0', 'id', 'Talenta teknis AI lintas bidang', 'Full-stack / Algoritma', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-efc2a5d0', 'vi', 'Nhân tài kỹ thuật AI liên ngành', 'Full-stack / Thuật toán', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-efc2a5d0', 'ar', 'كفاءات تقنية متعددة التخصصات في الذكاء الاصطناعي', 'تطوير متكامل / خوارزميات', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-cdccf456', 'en', 'Supercomputing Cluster Engineer', 'AI Core Systems', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-cdccf456', 'zh', '超算集群研发工程师', 'AI 核心系统研发', '北京、杭州', NULL, NULL),
  ('deepseek-cdccf456', 'ja', 'スーパーコンピュータクラスタエンジニア', 'AI コアシステム開発', '北京・杭州', NULL, NULL),
  ('deepseek-cdccf456', 'ko', '슈퍼컴퓨팅 클러스터 개발 엔지니어', 'AI 핵심 시스템 개발', '베이징 · 항저우', NULL, NULL),
  ('deepseek-cdccf456', 'es', 'Ingeniero de clústeres de supercomputación', 'Sistemas núcleo de IA', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-cdccf456', 'pt', 'Engenheiro de clusters de supercomputação', 'Sistemas centrais de IA', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-cdccf456', 'id', 'Engineer klaster superkomputer', 'Sistem inti AI', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-cdccf456', 'vi', 'Kỹ sư cụm siêu máy tính', 'Hệ thống lõi AI', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-cdccf456', 'ar', 'مهندس عناقيد الحوسبة الفائقة', 'أنظمة الذكاء الاصطناعي الأساسية', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-aed2a32c', 'en', 'High-performance Kernel / Communication / Compiler Engineer', 'AI Core Systems', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-aed2a32c', 'zh', '高性能算子/通信/编译器工程师', 'AI 核心系统研发', '北京、杭州', NULL, NULL),
  ('deepseek-aed2a32c', 'ja', '高性能カーネル / 通信 / コンパイラエンジニア', 'AI コアシステム開発', '北京・杭州', NULL, NULL),
  ('deepseek-aed2a32c', 'ko', '고성능 연산자/통신/컴파일러 엔지니어', 'AI 핵심 시스템 개발', '베이징 · 항저우', NULL, NULL),
  ('deepseek-aed2a32c', 'es', 'Ingeniero de kernels / comunicaciones / compiladores de alto rendimiento', 'Sistemas núcleo de IA', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-aed2a32c', 'pt', 'Engenheiro de kernels / comunicação / compiladores de alto desempenho', 'Sistemas centrais de IA', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-aed2a32c', 'id', 'Engineer kernel / komunikasi / compiler berkinerja tinggi', 'Sistem inti AI', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-aed2a32c', 'vi', 'Kỹ sư kernel / truyền thông / trình biên dịch hiệu năng cao', 'Hệ thống lõi AI', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-aed2a32c', 'ar', 'مهندس النوى / الاتصالات / المترجمات عالية الأداء', 'أنظمة الذكاء الاصطناعي الأساسية', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-a63f2346', 'en', 'R&D Infrastructure Engineer', 'AI Core Systems', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-a63f2346', 'zh', '研发基础设施工程师', 'AI 核心系统研发', '北京、杭州', NULL, NULL),
  ('deepseek-a63f2346', 'ja', '研究開発インフラエンジニア', 'AI コアシステム開発', '北京・杭州', NULL, NULL),
  ('deepseek-a63f2346', 'ko', 'R&D 인프라 엔지니어', 'AI 핵심 시스템 개발', '베이징 · 항저우', NULL, NULL),
  ('deepseek-a63f2346', 'es', 'Ingeniero de infraestructura de I+D', 'Sistemas núcleo de IA', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-a63f2346', 'pt', 'Engenheiro de infraestrutura de P&D', 'Sistemas centrais de IA', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-a63f2346', 'id', 'Engineer infrastruktur R&D', 'Sistem inti AI', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-a63f2346', 'vi', 'Kỹ sư hạ tầng R&D', 'Hệ thống lõi AI', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-a63f2346', 'ar', 'مهندس البنية التحتية للبحث والتطوير', 'أنظمة الذكاء الاصطناعي الأساسية', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-a7355097', 'en', 'High-performance Distributed Storage Engineer', 'AI Core Systems', 'Hangzhou', NULL, NULL),
  ('deepseek-a7355097', 'zh', '高性能分布式存储工程师', 'AI 核心系统研发', '杭州', NULL, NULL),
  ('deepseek-a7355097', 'ja', '高性能分散ストレージエンジニア', 'AI コアシステム開発', '杭州', NULL, NULL),
  ('deepseek-a7355097', 'ko', '고성능 분산 스토리지 엔지니어', 'AI 핵심 시스템 개발', '항저우', NULL, NULL),
  ('deepseek-a7355097', 'es', 'Ingeniero de almacenamiento distribuido de alto rendimiento', 'Sistemas núcleo de IA', 'Hangzhou', NULL, NULL),
  ('deepseek-a7355097', 'pt', 'Engenheiro de armazenamento distribuído de alto desempenho', 'Sistemas centrais de IA', 'Hangzhou', NULL, NULL),
  ('deepseek-a7355097', 'id', 'Engineer penyimpanan terdistribusi berkinerja tinggi', 'Sistem inti AI', 'Hangzhou', NULL, NULL),
  ('deepseek-a7355097', 'vi', 'Kỹ sư lưu trữ phân tán hiệu năng cao', 'Hệ thống lõi AI', 'Hàng Châu', NULL, NULL),
  ('deepseek-a7355097', 'ar', 'مهندس التخزين الموزع عالي الأداء', 'أنظمة الذكاء الاصطناعي الأساسية', 'هانغتشو', NULL, NULL),
  ('deepseek-b48bdca9', 'en', 'AI Platform Operations Engineer', 'Operations & Infrastructure', 'Hangzhou', NULL, NULL),
  ('deepseek-b48bdca9', 'zh', 'AI 平台运维工程师', '运维', '杭州', NULL, NULL),
  ('deepseek-b48bdca9', 'ja', 'AI プラットフォーム運用エンジニア', '運用・インフラ', '杭州', NULL, NULL),
  ('deepseek-b48bdca9', 'ko', 'AI 플랫폼 운영 엔지니어', '운영·인프라', '항저우', NULL, NULL),
  ('deepseek-b48bdca9', 'es', 'Ingeniero de operaciones de plataforma de IA', 'Operaciones e infraestructura', 'Hangzhou', NULL, NULL),
  ('deepseek-b48bdca9', 'pt', 'Engenheiro de operações de plataforma de IA', 'Operações e infraestrutura', 'Hangzhou', NULL, NULL),
  ('deepseek-b48bdca9', 'id', 'Engineer operasional platform AI', 'Operasional & infrastruktur', 'Hangzhou', NULL, NULL),
  ('deepseek-b48bdca9', 'vi', 'Kỹ sư vận hành nền tảng AI', 'Vận hành & hạ tầng', 'Hàng Châu', NULL, NULL),
  ('deepseek-b48bdca9', 'ar', 'مهندس عمليات منصة الذكاء الاصطناعي', 'العمليات والبنية التحتية', 'هانغتشو', NULL, NULL),
  ('deepseek-27f0675d', 'en', 'IT Infrastructure Team', 'Operations & Infrastructure', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-27f0675d', 'zh', 'IT 基础设施团队', '运维', '北京、杭州', NULL, NULL),
  ('deepseek-27f0675d', 'ja', 'IT インフラチーム', '運用・インフラ', '北京・杭州', NULL, NULL),
  ('deepseek-27f0675d', 'ko', 'IT 인프라 팀', '운영·인프라', '베이징 · 항저우', NULL, NULL),
  ('deepseek-27f0675d', 'es', 'Equipo de infraestructura TI', 'Operaciones e infraestructura', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-27f0675d', 'pt', 'Equipe de infraestrutura de TI', 'Operações e infraestrutura', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-27f0675d', 'id', 'Tim infrastruktur TI', 'Operasional & infrastruktur', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-27f0675d', 'vi', 'Nhóm hạ tầng CNTT', 'Vận hành & hạ tầng', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-27f0675d', 'ar', 'فريق البنية التحتية لتقنية المعلومات', 'العمليات والبنية التحتية', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-1c7e328d', 'en', 'IDC Data Center Team', 'Operations & Infrastructure', 'Beijing / Hangzhou / Ulanqab', NULL, NULL),
  ('deepseek-1c7e328d', 'zh', 'IDC 数据中心团队', '运维', '北京、杭州、乌兰察布', NULL, NULL),
  ('deepseek-1c7e328d', 'ja', 'IDC データセンターチーム', '運用・インフラ', '北京・杭州・ウランチャブ', NULL, NULL),
  ('deepseek-1c7e328d', 'ko', 'IDC 데이터센터 팀', '운영·인프라', '베이징 · 항저우 · 울란차부', NULL, NULL),
  ('deepseek-1c7e328d', 'es', 'Equipo de centros de datos (IDC)', 'Operaciones e infraestructura', 'Pekín / Hangzhou / Ulanqab', NULL, NULL),
  ('deepseek-1c7e328d', 'pt', 'Equipe de data center (IDC)', 'Operações e infraestrutura', 'Pequim / Hangzhou / Ulanqab', NULL, NULL),
  ('deepseek-1c7e328d', 'id', 'Tim pusat data IDC', 'Operasional & infrastruktur', 'Beijing / Hangzhou / Ulanqab', NULL, NULL),
  ('deepseek-1c7e328d', 'vi', 'Nhóm trung tâm dữ liệu IDC', 'Vận hành & hạ tầng', 'Bắc Kinh / Hàng Châu / Ô Lan Sát Bố', NULL, NULL),
  ('deepseek-1c7e328d', 'ar', 'فريق مراكز البيانات IDC', 'العمليات والبنية التحتية', 'بكين / هانغتشو / أولانتشاب', NULL, NULL),
  ('deepseek-e8f2004c', 'en', 'AI Product Manager', 'Product', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-e8f2004c', 'zh', 'AI 产品经理', '产品部门', '北京、杭州', NULL, NULL),
  ('deepseek-e8f2004c', 'ja', 'AI プロダクトマネージャー', 'プロダクト', '北京・杭州', NULL, NULL),
  ('deepseek-e8f2004c', 'ko', 'AI 프로덕트 매니저', '프로덕트', '베이징 · 항저우', NULL, NULL),
  ('deepseek-e8f2004c', 'es', 'Product manager de IA', 'Producto', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-e8f2004c', 'pt', 'Gerente de produto de IA', 'Produto', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-e8f2004c', 'id', 'Product manager AI', 'Produk', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-e8f2004c', 'vi', 'Quản lý sản phẩm AI', 'Sản phẩm', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-e8f2004c', 'ar', 'مدير منتجات الذكاء الاصطناعي', 'المنتج', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-d6cff61d', 'en', 'Operations Team', 'Product', 'Beijing', NULL, NULL),
  ('deepseek-d6cff61d', 'zh', '运营团队', '产品部门', '北京', NULL, NULL),
  ('deepseek-d6cff61d', 'ja', 'オペレーションチーム', 'プロダクト', '北京', NULL, NULL),
  ('deepseek-d6cff61d', 'ko', '운영 팀', '프로덕트', '베이징', NULL, NULL),
  ('deepseek-d6cff61d', 'es', 'Equipo de operaciones', 'Producto', 'Pekín', NULL, NULL),
  ('deepseek-d6cff61d', 'pt', 'Equipe de operações', 'Produto', 'Pequim', NULL, NULL),
  ('deepseek-d6cff61d', 'id', 'Tim operasional', 'Produk', 'Beijing', NULL, NULL),
  ('deepseek-d6cff61d', 'vi', 'Nhóm vận hành', 'Sản phẩm', 'Bắc Kinh', NULL, NULL),
  ('deepseek-d6cff61d', 'ar', 'فريق العمليات', 'المنتج', 'بكين', NULL, NULL),
  ('deepseek-a4ad8628', 'en', 'Code Agent Data Engineer', 'Model Data Strategy', 'Beijing', NULL, NULL),
  ('deepseek-a4ad8628', 'zh', 'Code Agent 数据工程师', '模型数据策略', '北京', NULL, NULL),
  ('deepseek-a4ad8628', 'ja', 'Code Agent データエンジニア', 'モデルデータ戦略', '北京', NULL, NULL),
  ('deepseek-a4ad8628', 'ko', 'Code Agent 데이터 엔지니어', '모델 데이터 전략', '베이징', NULL, NULL),
  ('deepseek-a4ad8628', 'es', 'Ingeniero de datos de Code Agent', 'Estrategia de datos de modelos', 'Pekín', NULL, NULL),
  ('deepseek-a4ad8628', 'pt', 'Engenheiro de dados de Code Agent', 'Estratégia de dados de modelos', 'Pequim', NULL, NULL),
  ('deepseek-a4ad8628', 'id', 'Engineer data Code Agent', 'Strategi data model', 'Beijing', NULL, NULL),
  ('deepseek-a4ad8628', 'vi', 'Kỹ sư dữ liệu Code Agent', 'Chiến lược dữ liệu mô hình', 'Bắc Kinh', NULL, NULL),
  ('deepseek-a4ad8628', 'ar', 'مهندس بيانات Code Agent', 'استراتيجية بيانات النماذج', 'بكين', NULL, NULL),
  ('deepseek-bdffaaf8', 'en', 'General Agent Data PM (Office / Life / Search)', 'Model Data Strategy', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-bdffaaf8', 'zh', '通用 Agent 数据产品经理（办公/生活/搜索）', '模型数据策略', '北京、杭州', NULL, NULL),
  ('deepseek-bdffaaf8', 'ja', '汎用 Agent データ PM（オフィス / 生活 / 検索）', 'モデルデータ戦略', '北京・杭州', NULL, NULL),
  ('deepseek-bdffaaf8', 'ko', '범용 Agent 데이터 PM (오피스/생활/검색)', '모델 데이터 전략', '베이징 · 항저우', NULL, NULL),
  ('deepseek-bdffaaf8', 'es', 'PM de datos de agentes generales (oficina / vida / búsqueda)', 'Estrategia de datos de modelos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-bdffaaf8', 'pt', 'PM de dados de agentes gerais (escritório / vida / busca)', 'Estratégia de dados de modelos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-bdffaaf8', 'id', 'PM data Agent umum (kantor / kehidupan / pencarian)', 'Strategi data model', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-bdffaaf8', 'vi', 'PM dữ liệu Agent đa năng (văn phòng / đời sống / tìm kiếm)', 'Chiến lược dữ liệu mô hình', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-bdffaaf8', 'ar', 'مدير منتجات بيانات الوكلاء العامة (المكتب / الحياة / البحث)', 'استراتيجية بيانات النماذج', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-141a78cd', 'en', 'Domain Data PM (minor languages, medicine, law, etc.)', 'Model Data Strategy', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-141a78cd', 'zh', '专业领域数据产品经理（小语种、医学法律等学科）', '模型数据策略', '北京、杭州', NULL, NULL),
  ('deepseek-141a78cd', 'ja', '専門領域データ PM（少数言語・医学・法律など）', 'モデルデータ戦略', '北京・杭州', NULL, NULL),
  ('deepseek-141a78cd', 'ko', '전문 분야 데이터 PM (소수 언어·의학·법률 등)', '모델 데이터 전략', '베이징 · 항저우', NULL, NULL),
  ('deepseek-141a78cd', 'es', 'PM de datos de dominios especializados (idiomas minoritarios, medicina, derecho…)', 'Estrategia de datos de modelos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-141a78cd', 'pt', 'PM de dados de domínios especializados (idiomas minoritários, medicina, direito…)', 'Estratégia de dados de modelos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-141a78cd', 'id', 'PM data domain khusus (bahasa minor, kedokteran, hukum, dll.)', 'Strategi data model', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-141a78cd', 'vi', 'PM dữ liệu chuyên ngành (ngôn ngữ ít phổ biến, y khoa, luật…)', 'Chiến lược dữ liệu mô hình', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-141a78cd', 'ar', 'مدير منتجات بيانات المجالات المتخصصة (اللغات النادرة، الطب، القانون…)', 'استراتيجية بيانات النماذج', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-0238c1b1', 'en', 'AI Creative Data PM', 'Model Data Strategy', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-0238c1b1', 'zh', 'AI 创作数据产品经理', '模型数据策略', '北京、杭州', NULL, NULL),
  ('deepseek-0238c1b1', 'ja', 'AI クリエイティブデータ PM', 'モデルデータ戦略', '北京・杭州', NULL, NULL),
  ('deepseek-0238c1b1', 'ko', 'AI 창작 데이터 PM', '모델 데이터 전략', '베이징 · 항저우', NULL, NULL),
  ('deepseek-0238c1b1', 'es', 'PM de datos creativos de IA', 'Estrategia de datos de modelos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-0238c1b1', 'pt', 'PM de dados criativos de IA', 'Estratégia de dados de modelos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-0238c1b1', 'id', 'PM data kreatif AI', 'Strategi data model', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-0238c1b1', 'vi', 'PM dữ liệu sáng tạo AI', 'Chiến lược dữ liệu mô hình', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-0238c1b1', 'ar', 'مدير منتجات بيانات الإبداع بالذكاء الاصطناعي', 'استراتيجية بيانات النماذج', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-b8e62d9e', 'en', 'Emotional Intelligence Data PM', 'Model Data Strategy', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-b8e62d9e', 'zh', '情感智能数据产品经理', '模型数据策略', '北京、杭州', NULL, NULL),
  ('deepseek-b8e62d9e', 'ja', '感情知能データ PM', 'モデルデータ戦略', '北京・杭州', NULL, NULL),
  ('deepseek-b8e62d9e', 'ko', '감성 지능 데이터 PM', '모델 데이터 전략', '베이징 · 항저우', NULL, NULL),
  ('deepseek-b8e62d9e', 'es', 'PM de datos de inteligencia emocional', 'Estrategia de datos de modelos', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-b8e62d9e', 'pt', 'PM de dados de inteligência emocional', 'Estratégia de dados de modelos', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-b8e62d9e', 'id', 'PM data kecerdasan emosional', 'Strategi data model', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-b8e62d9e', 'vi', 'PM dữ liệu trí tuệ cảm xúc', 'Chiến lược dữ liệu mô hình', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-b8e62d9e', 'ar', 'مدير منتجات بيانات الذكاء العاطفي', 'استراتيجية بيانات النماذج', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-c7076ca9', 'en', 'Frontier Researcher (continual learning / self-evolution / new paradigms)', 'Deep Learning Research', 'Beijing', NULL, NULL),
  ('deepseek-c7076ca9', 'zh', 'Frontier（持续学习/自进化/新范式）研究员', '深度学习研究员', '北京', NULL, NULL),
  ('deepseek-c7076ca9', 'ja', 'Frontier 研究員（継続学習 / 自己進化 / 新パラダイム）', '深層学習リサーチ', '北京', NULL, NULL),
  ('deepseek-c7076ca9', 'ko', 'Frontier 연구원 (지속 학습/자기 진화/새 패러다임)', '딥러닝 연구', '베이징', NULL, NULL),
  ('deepseek-c7076ca9', 'es', 'Investigador Frontier (aprendizaje continuo / autoevolución / nuevos paradigmas)', 'Investigación en deep learning', 'Pekín', NULL, NULL),
  ('deepseek-c7076ca9', 'pt', 'Pesquisador Frontier (aprendizado contínuo / autoevolução / novos paradigmas)', 'Pesquisa em deep learning', 'Pequim', NULL, NULL),
  ('deepseek-c7076ca9', 'id', 'Peneliti Frontier (continual learning / evolusi diri / paradigma baru)', 'Riset deep learning', 'Beijing', NULL, NULL),
  ('deepseek-c7076ca9', 'vi', 'Nhà nghiên cứu Frontier (học liên tục / tự tiến hóa / mô hình mới)', 'Nghiên cứu học sâu', 'Bắc Kinh', NULL, NULL),
  ('deepseek-c7076ca9', 'ar', 'باحث Frontier (التعلم المستمر / التطور الذاتي / نماذج جديدة)', 'أبحاث التعلم العميق', 'بكين', NULL, NULL),
  ('deepseek-25dcb4d9', 'en', 'Pre-training Researcher (data / algorithms)', 'Deep Learning Research', 'Beijing', NULL, NULL),
  ('deepseek-25dcb4d9', 'zh', '预训练（数据/算法）研究员', '深度学习研究员', '北京', NULL, NULL),
  ('deepseek-25dcb4d9', 'ja', '事前学習研究員（データ / アルゴリズム）', '深層学習リサーチ', '北京', NULL, NULL),
  ('deepseek-25dcb4d9', 'ko', '사전학습 연구원 (데이터/알고리즘)', '딥러닝 연구', '베이징', NULL, NULL),
  ('deepseek-25dcb4d9', 'es', 'Investigador de preentrenamiento (datos / algoritmos)', 'Investigación en deep learning', 'Pekín', NULL, NULL),
  ('deepseek-25dcb4d9', 'pt', 'Pesquisador de pré-treinamento (dados / algoritmos)', 'Pesquisa em deep learning', 'Pequim', NULL, NULL),
  ('deepseek-25dcb4d9', 'id', 'Peneliti pre-training (data / algoritma)', 'Riset deep learning', 'Beijing', NULL, NULL),
  ('deepseek-25dcb4d9', 'vi', 'Nhà nghiên cứu tiền huấn luyện (dữ liệu / thuật toán)', 'Nghiên cứu học sâu', 'Bắc Kinh', NULL, NULL),
  ('deepseek-25dcb4d9', 'ar', 'باحث التدريب المسبق (البيانات / الخوارزميات)', 'أبحاث التعلم العميق', 'بكين', NULL, NULL),
  ('deepseek-5d75f4cd', 'en', 'Post-training Researcher (data / algorithms)', 'Deep Learning Research', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-5d75f4cd', 'zh', '后训练（数据/算法）研究员', '深度学习研究员', '北京、杭州', NULL, NULL),
  ('deepseek-5d75f4cd', 'ja', '事後学習研究員（データ / アルゴリズム）', '深層学習リサーチ', '北京・杭州', NULL, NULL),
  ('deepseek-5d75f4cd', 'ko', '사후학습 연구원 (데이터/알고리즘)', '딥러닝 연구', '베이징 · 항저우', NULL, NULL),
  ('deepseek-5d75f4cd', 'es', 'Investigador de postentrenamiento (datos / algoritmos)', 'Investigación en deep learning', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-5d75f4cd', 'pt', 'Pesquisador de pós-treinamento (dados / algoritmos)', 'Pesquisa em deep learning', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-5d75f4cd', 'id', 'Peneliti post-training (data / algoritma)', 'Riset deep learning', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-5d75f4cd', 'vi', 'Nhà nghiên cứu hậu huấn luyện (dữ liệu / thuật toán)', 'Nghiên cứu học sâu', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-5d75f4cd', 'ar', 'باحث ما بعد التدريب (البيانات / الخوارزميات)', 'أبحاث التعلم العميق', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-7dcd6fde', 'en', 'Multimodal Understanding Researcher (data / algorithms)', 'Deep Learning Research', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-7dcd6fde', 'zh', '多模态理解（数据/算法）研究员', '深度学习研究员', '北京、杭州', NULL, NULL),
  ('deepseek-7dcd6fde', 'ja', 'マルチモーダル理解研究員（データ / アルゴリズム）', '深層学習リサーチ', '北京・杭州', NULL, NULL),
  ('deepseek-7dcd6fde', 'ko', '멀티모달 이해 연구원 (데이터/알고리즘)', '딥러닝 연구', '베이징 · 항저우', NULL, NULL),
  ('deepseek-7dcd6fde', 'es', 'Investigador de comprensión multimodal (datos / algoritmos)', 'Investigación en deep learning', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-7dcd6fde', 'pt', 'Pesquisador de compreensão multimodal (dados / algoritmos)', 'Pesquisa em deep learning', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-7dcd6fde', 'id', 'Peneliti pemahaman multimodal (data / algoritma)', 'Riset deep learning', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-7dcd6fde', 'vi', 'Nhà nghiên cứu hiểu đa phương thức (dữ liệu / thuật toán)', 'Nghiên cứu học sâu', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-7dcd6fde', 'ar', 'باحث الفهم متعدد الوسائط (البيانات / الخوارزميات)', 'أبحاث التعلم العميق', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-647a8853', 'en', 'AGI Core Business Management Trainee', 'Corporate Functions', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-647a8853', 'zh', 'AGI 核心业务管培生', '职能部门', '北京、杭州', NULL, NULL),
  ('deepseek-647a8853', 'ja', 'AGI コア事業マネジメントトレーニー', 'コーポレート部門', '北京・杭州', NULL, NULL),
  ('deepseek-647a8853', 'ko', 'AGI 핵심 사업 관리 연수생', '경영지원', '베이징 · 항저우', NULL, NULL),
  ('deepseek-647a8853', 'es', 'Trainee de gestión del negocio central de AGI', 'Funciones corporativas', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-647a8853', 'pt', 'Trainee de gestão do negócio central de AGI', 'Funções corporativas', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-647a8853', 'id', 'Management trainee bisnis inti AGI', 'Fungsi korporat', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-647a8853', 'vi', 'Quản trị viên tập sự mảng kinh doanh cốt lõi AGI', 'Khối chức năng', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-647a8853', 'ar', 'متدرب إداري في أعمال AGI الأساسية', 'الوظائف المؤسسية', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-08d2d307', 'en', 'HR Team', 'Corporate Functions', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-08d2d307', 'zh', 'HR 团队', '职能部门', '北京、杭州', NULL, NULL),
  ('deepseek-08d2d307', 'ja', '人事チーム', 'コーポレート部門', '北京・杭州', NULL, NULL),
  ('deepseek-08d2d307', 'ko', 'HR 팀', '경영지원', '베이징 · 항저우', NULL, NULL),
  ('deepseek-08d2d307', 'es', 'Equipo de RR. HH.', 'Funciones corporativas', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-08d2d307', 'pt', 'Equipe de RH', 'Funções corporativas', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-08d2d307', 'id', 'Tim HR', 'Fungsi korporat', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-08d2d307', 'vi', 'Nhóm nhân sự', 'Khối chức năng', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-08d2d307', 'ar', 'فريق الموارد البشرية', 'الوظائف المؤسسية', 'بكين / هانغتشو', NULL, NULL),
  ('deepseek-7dfbdfc9', 'en', 'Legal Team', 'Corporate Functions', 'Hangzhou', NULL, NULL),
  ('deepseek-7dfbdfc9', 'zh', '法务团队', '职能部门', '杭州', NULL, NULL),
  ('deepseek-7dfbdfc9', 'ja', '法務チーム', 'コーポレート部門', '杭州', NULL, NULL),
  ('deepseek-7dfbdfc9', 'ko', '법무 팀', '경영지원', '항저우', NULL, NULL),
  ('deepseek-7dfbdfc9', 'es', 'Equipo legal', 'Funciones corporativas', 'Hangzhou', NULL, NULL),
  ('deepseek-7dfbdfc9', 'pt', 'Equipe jurídica', 'Funções corporativas', 'Hangzhou', NULL, NULL),
  ('deepseek-7dfbdfc9', 'id', 'Tim hukum', 'Fungsi korporat', 'Hangzhou', NULL, NULL),
  ('deepseek-7dfbdfc9', 'vi', 'Nhóm pháp chế', 'Khối chức năng', 'Hàng Châu', NULL, NULL),
  ('deepseek-7dfbdfc9', 'ar', 'الفريق القانوني', 'الوظائف المؤسسية', 'هانغتشو', NULL, NULL),
  ('deepseek-2f6838b7', 'en', 'Finance Team', 'Corporate Functions', 'Hangzhou', NULL, NULL),
  ('deepseek-2f6838b7', 'zh', '财务团队', '职能部门', '杭州', NULL, NULL),
  ('deepseek-2f6838b7', 'ja', '財務チーム', 'コーポレート部門', '杭州', NULL, NULL),
  ('deepseek-2f6838b7', 'ko', '재무 팀', '경영지원', '항저우', NULL, NULL),
  ('deepseek-2f6838b7', 'es', 'Equipo de finanzas', 'Funciones corporativas', 'Hangzhou', NULL, NULL),
  ('deepseek-2f6838b7', 'pt', 'Equipe financeira', 'Funções corporativas', 'Hangzhou', NULL, NULL),
  ('deepseek-2f6838b7', 'id', 'Tim keuangan', 'Fungsi korporat', 'Hangzhou', NULL, NULL),
  ('deepseek-2f6838b7', 'vi', 'Nhóm tài chính', 'Khối chức năng', 'Hàng Châu', NULL, NULL),
  ('deepseek-2f6838b7', 'ar', 'الفريق المالي', 'الوظائف المؤسسية', 'هانغتشو', NULL, NULL),
  ('deepseek-97ecb322', 'en', 'Procurement Team', 'Corporate Functions', 'Hangzhou / Ulanqab', NULL, NULL),
  ('deepseek-97ecb322', 'zh', '采购团队', '职能部门', '杭州、乌兰察布', NULL, NULL),
  ('deepseek-97ecb322', 'ja', '調達チーム', 'コーポレート部門', '杭州・ウランチャブ', NULL, NULL),
  ('deepseek-97ecb322', 'ko', '구매 팀', '경영지원', '항저우 · 울란차부', NULL, NULL),
  ('deepseek-97ecb322', 'es', 'Equipo de compras', 'Funciones corporativas', 'Hangzhou / Ulanqab', NULL, NULL),
  ('deepseek-97ecb322', 'pt', 'Equipe de compras', 'Funções corporativas', 'Hangzhou / Ulanqab', NULL, NULL),
  ('deepseek-97ecb322', 'id', 'Tim pengadaan', 'Fungsi korporat', 'Hangzhou / Ulanqab', NULL, NULL),
  ('deepseek-97ecb322', 'vi', 'Nhóm mua hàng', 'Khối chức năng', 'Hàng Châu / Ô Lan Sát Bố', NULL, NULL),
  ('deepseek-97ecb322', 'ar', 'فريق المشتريات', 'الوظائف المؤسسية', 'هانغتشو / أولانتشاب', NULL, NULL),
  ('deepseek-a7a0d39e', 'en', 'Administration Team', 'Corporate Functions', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-a7a0d39e', 'zh', '行政团队', '职能部门', '北京、杭州', NULL, NULL),
  ('deepseek-a7a0d39e', 'ja', '総務チーム', 'コーポレート部門', '北京・杭州', NULL, NULL),
  ('deepseek-a7a0d39e', 'ko', '총무 팀', '경영지원', '베이징 · 항저우', NULL, NULL),
  ('deepseek-a7a0d39e', 'es', 'Equipo de administración', 'Funciones corporativas', 'Pekín / Hangzhou', NULL, NULL),
  ('deepseek-a7a0d39e', 'pt', 'Equipe administrativa', 'Funções corporativas', 'Pequim / Hangzhou', NULL, NULL),
  ('deepseek-a7a0d39e', 'id', 'Tim administrasi', 'Fungsi korporat', 'Beijing / Hangzhou', NULL, NULL),
  ('deepseek-a7a0d39e', 'vi', 'Nhóm hành chính', 'Khối chức năng', 'Bắc Kinh / Hàng Châu', NULL, NULL),
  ('deepseek-a7a0d39e', 'ar', 'الفريق الإداري', 'الوظائف المؤسسية', 'بكين / هانغتشو', NULL, NULL);
