/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false` (hash: 0194c0c17f27e55bc85301b81eeb74fe)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	CF_ACCOUNT_ID: "8f19bebe359e4ec1a24c68c5f49c1584";
	ALERT_FROM: "alerts@mail.ghfind.com";
	HOURLY_WARNING_USD: "0.5";
	HOURLY_CRITICAL_USD: "2";
	DAILY_WARNING_USD: "10";
	MONITOR: DurableObjectNamespace<import("./src/index").CostMonitor>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CostMonitor";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCOUNT_ID" | "ALERT_FROM" | "HOURLY_WARNING_USD" | "HOURLY_CRITICAL_USD" | "DAILY_WARNING_USD">> {}
}
