import type { LeaderboardClientEntry, LeaderboardView } from "./LeaderboardClient";

const DEV_PREVIEW_ENTRIES: LeaderboardClientEntry[] = [
  {
    username: "kernel-whisperer-very-long-name",
    display_name: "Linux 之父候选人",
    avatar_url: null,
    profile_url: "https://github.com/kernel-whisperer-very-long-name",
    final_score: 95,
    tier: "夯",
    tags: {
      zh: ["Linux 之父", "开源趋势顶流", "潜水极客", "内核考古学家"],
      en: ["Linux elder", "open-source trend", "quiet operator", "kernel archaeologist"],
    },
    lookup_count: 146,
    recent_lookup_count: 28,
    trending_score: 93.7,
    prev_score: 88.4,
    delta: 6.6,
  },
  {
    username: "rss-syntax-samurai",
    display_name: "RSS 教父",
    avatar_url: null,
    profile_url: "https://github.com/rss-syntax-samurai",
    final_score: 93.8,
    tier: "顶级",
    tags: {
      zh: ["RSS 教父", "开源劳模", "全栈大佬", "协议洁癖"],
      en: ["RSS mentor", "open-source workhorse", "full-stack senior", "protocol purist"],
    },
    lookup_count: 5,
    recent_lookup_count: 5,
    trending_score: 100,
    prev_score: 85.6,
    delta: 8.2,
  },
  {
    username: "swift-ai-researcher-cn",
    display_name: "AI 弄潮儿",
    avatar_url: null,
    profile_url: "https://github.com/swift-ai-researcher-cn",
    final_score: 93.6,
    tier: "顶级",
    tags: {
      zh: ["开源老炮", "AI 弄潮儿", "Swift 狂热者", "模型搬砖王"],
      en: ["open-source veteran", "AI builder", "Swift fan", "model wrangler"],
    },
    lookup_count: 6,
    recent_lookup_count: 4,
    trending_score: 99.3,
    prev_score: 91.1,
    delta: 2.5,
  },
  {
    username: "frontend-cache-surgeon",
    display_name: "缓存外科医生",
    avatar_url: null,
    profile_url: "https://github.com/frontend-cache-surgeon",
    final_score: 91.2,
    tier: "顶级",
    tags: {
      zh: ["前端性能党", "缓存外科医生", "构建系统洁癖"],
      en: ["frontend perf", "cache surgeon", "build-system purist"],
    },
    lookup_count: 82,
    recent_lookup_count: 16,
    trending_score: 89.4,
    prev_score: 89.9,
    delta: 1.3,
  },
  {
    username: "cli-turborepo-maintainer",
    display_name: "CLI 体力活冠军",
    avatar_url: null,
    profile_url: "https://github.com/cli-turborepo-maintainer",
    final_score: 88.7,
    tier: "人上人",
    tags: {
      zh: ["CLI 苦工", "Monorepo 管家", "发布脚本大师"],
      en: ["CLI grinder", "monorepo steward", "release-script master"],
    },
    lookup_count: 61,
    recent_lookup_count: 9,
    trending_score: 82.1,
    prev_score: 79.2,
    delta: 9.5,
  },
  {
    username: "database-index-detective",
    display_name: "索引侦探",
    avatar_url: null,
    profile_url: "https://github.com/database-index-detective",
    final_score: 86.4,
    tier: "人上人",
    tags: {
      zh: ["数据库老兵", "索引侦探", "慢查询清道夫"],
      en: ["database veteran", "index detective", "slow-query fixer"],
    },
    lookup_count: 37,
    recent_lookup_count: 7,
    trending_score: 79.8,
    prev_score: 84.2,
    delta: 2.2,
  },
  {
    username: "docs-driven-architect",
    display_name: "文档驱动架构师",
    avatar_url: null,
    profile_url: "https://github.com/docs-driven-architect",
    final_score: 84.9,
    tier: "人上人",
    tags: {
      zh: ["文档驱动", "API 洁癖", "长文档幸存者"],
      en: ["docs-driven", "API purist", "long-doc survivor"],
    },
    lookup_count: 44,
    recent_lookup_count: 11,
    trending_score: 81.5,
    prev_score: 80.7,
    delta: 4.2,
  },
  {
    username: "issue-triage-night-shift",
    display_name: "夜班维护者",
    avatar_url: null,
    profile_url: "https://github.com/issue-triage-night-shift",
    final_score: 81.3,
    tier: "人上人",
    tags: {
      zh: ["Issue 清道夫", "夜班维护者", "复现狂魔"],
      en: ["issue triage", "night-shift maintainer", "repro hunter"],
    },
    lookup_count: 25,
    recent_lookup_count: 13,
    trending_score: 78.2,
    prev_score: 75.5,
    delta: 5.8,
  },
  {
    username: "fork-hoarder-redemption",
    display_name: "Fork 收藏家",
    avatar_url: null,
    profile_url: "https://github.com/fork-hoarder-redemption",
    final_score: 73.5,
    tier: "NPC",
    tags: {
      zh: ["收藏夹战神", "偶尔发光", "README 修补匠"],
      en: ["fork collector", "occasional spark", "README patcher"],
    },
    lookup_count: 19,
    recent_lookup_count: 6,
    trending_score: 66.9,
    prev_score: 72,
    delta: 1.5,
  },
  {
    username: "template-pr-recovering-bot",
    display_name: "模板 PR 康复中",
    avatar_url: null,
    profile_url: "https://github.com/template-pr-recovering-bot",
    final_score: 64.2,
    tier: "NPC",
    tags: {
      zh: ["模板 PR 康复中", "刷题边缘", "偶尔认真"],
      en: ["template PR rehab", "borderline grinder", "sometimes serious"],
    },
    lookup_count: 33,
    recent_lookup_count: 8,
    trending_score: 62.4,
    prev_score: 57.1,
    delta: 7.1,
  },
];

const PREVIEW_BY_VIEW: Record<LeaderboardView, LeaderboardClientEntry[]> = {
  trending: [...DEV_PREVIEW_ENTRIES].sort((a, b) => b.trending_score - a.trending_score),
  score: [...DEV_PREVIEW_ENTRIES].sort((a, b) => b.final_score - a.final_score),
  heat: [...DEV_PREVIEW_ENTRIES].sort((a, b) => b.lookup_count - a.lookup_count),
};

export function withDevLeaderboardPreview(
  view: LeaderboardView,
  entries: LeaderboardClientEntry[],
): LeaderboardClientEntry[] {
  if (process.env.NODE_ENV !== "development" || entries.length > 0) {
    return entries;
  }

  return PREVIEW_BY_VIEW[view];
}
